version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/src/frontend"
    schedule:
      interval: "weekly"
    groups:
      npm-all:
        patterns:
          - "*"
