import containerImagesData from '@data/container-images.json';
import integrationDocsData from '@data/integration-docs.json';

/**
 * A single container image reference extracted from the `microsoft/aspire`
 * hosting integrations. The data file is generated by the `container-images`
 * skill from the `*ContainerImageTags.cs` source files.
 */
export interface ContainerImage {
  /** The hosting NuGet package / project name (e.g. `Aspire.Hosting.Redis`). */
  aspirePackage: string;
  /** Human-friendly image name (e.g. `Redis`, `Redis Commander`). */
  name: string;
  /** Container registry host (e.g. `docker.io`, `mcr.microsoft.com`). */
  registry: string;
  /** Image path within the registry (e.g. `library/redis`). */
  image: string;
  /** Primary tag (e.g. `8.6`). */
  tag: string;
  /** Fully qualified reference: `{registry}/{image}:{tag}`. */
  fullImage: string;
  /** Path to the source file in `microsoft/aspire`, relative to the repo root. */
  sourceFile: string;
  /** GitHub permalink to the source file on the `main` branch. */
  sourceUrl: string;
  /** `true` when this is a companion/tooling image (pgAdmin, Kafka UI, etc.). */
  isCompanion: boolean;
  /** Name of the primary image this accompanies, or `null`. */
  companionOf: string | null;
  /**
   * AppHost API that introduces this image, without parentheses (e.g.
   * `AddPostgres`, `WithPgAdmin`, `RunAsEmulator`), or `null` if not known.
   */
  api: string | null;
  /** Additional tag variants defined for this image (e.g. `vnext-latest`). */
  alternateTags: string[];
}

/** All container images, sorted by package then primary-first then name. */
export const containerImages = containerImagesData as ContainerImage[];

/**
 * Return the container images for a hosting package, preserving the data
 * file's order (primary image first, then companions).
 *
 * @param aspirePackage Exact package name, e.g. `Aspire.Hosting.PostgreSQL`.
 * @param only Optional image `name` (or list of names) to include. Matching is
 *   case-insensitive, so `only="pgAdmin"` selects just the pgAdmin companion.
 */
export function getContainerImages(
  aspirePackage: string,
  only?: string | string[],
): ContainerImage[] {
  const allowed =
    only == null
      ? null
      : (Array.isArray(only) ? only : [only]).map((name) => name.toLowerCase());

  return containerImages.filter((img) => {
    if (img.aspirePackage !== aspirePackage) {
      return false;
    }
    if (allowed && !allowed.includes(img.name.toLowerCase())) {
      return false;
    }
    return true;
  });
}

/**
 * Best-effort web URL for the registry catalog page of an image (Docker Hub,
 * MCR, GHCR, Quay, Oracle). Returns `null` for unrecognized registries so the
 * caller can fall back to the source-file link.
 */
export function getRegistryUrl(img: Pick<ContainerImage, 'registry' | 'image'>): string | null {
  const { registry, image } = img;
  switch (registry) {
    case 'docker.io':
      // Official images live under `library/`; everything else is `owner/name`.
      return image.startsWith('library/')
        ? `https://hub.docker.com/_/${image.slice('library/'.length)}`
        : `https://hub.docker.com/r/${image}`;
    case 'mcr.microsoft.com':
      return `https://mcr.microsoft.com/en-us/product/${image}/about`;
    case 'quay.io':
      return `https://quay.io/repository/${image}`;
    case 'ghcr.io': {
      const parts = image.split('/');
      const owner = parts[0];
      const name = parts[parts.length - 1];
      return owner && name
        ? `https://github.com/${owner}/${name}/pkgs/container/${name}`
        : null;
    }
    case 'container-registry.oracle.com':
      return `https://container-registry.oracle.com/ords/ocr/ba/${image}`;
    default:
      return null;
  }
}

/** Short, human-friendly label for a registry host. */
export function getRegistryLabel(registry: string): string {
  switch (registry) {
    case 'docker.io':
      return 'Docker Hub';
    case 'mcr.microsoft.com':
      return 'Microsoft Artifact Registry';
    case 'ghcr.io':
      return 'GitHub Container Registry';
    case 'quay.io':
      return 'Quay.io';
    case 'container-registry.oracle.com':
      return 'Oracle Container Registry';
    default:
      return registry;
  }
}

/** `{ match, href }` entry from the generated integration-docs data file. */
interface IntegrationDoc {
  match: string;
  href: string;
}

const integrationHrefByPackage = new Map(
  (integrationDocsData as IntegrationDoc[]).map((doc) => [doc.match, doc.href]),
);

/**
 * Docs URL for the hosting integration that ships an image, e.g.
 * `/integrations/databases/postgres/postgres-get-started/`. Returns `null` when
 * the package has no matching docs entry.
 */
export function getIntegrationHref(aspirePackage: string): string | null {
  return integrationHrefByPackage.get(aspirePackage) ?? null;
}

// Friendly labels + display order for the catalog's category headings. Keys are
// derived from each integration's docs href (`/integrations/<key>/...`), with
// `cloud` deepened to its provider segment (`cloud/azure` -> `azure`).
const CATEGORY_LABELS: Record<string, string> = {
  databases: 'Databases',
  caching: 'Caching',
  messaging: 'Messaging',
  observability: 'Observability',
  security: 'Security',
  'reverse-proxies': 'Reverse proxies',
  azure: 'Azure emulators',
};

const CATEGORY_ORDER = [
  'databases',
  'caching',
  'messaging',
  'observability',
  'security',
  'reverse-proxies',
  'azure',
];

function titleCase(key: string): string {
  return key.replace(
    /(^|[-\s])(\w)/g,
    (_match: string, sep: string, ch: string) => `${sep === '-' ? ' ' : sep}${ch.toUpperCase()}`,
  );
}

/**
 * Derive a catalog category key for a hosting package from the site's own
 * information architecture (its docs href), so new integrations are categorized
 * automatically without a hand-maintained package map.
 */
function categoryKeyFor(aspirePackage: string): string {
  const href = integrationHrefByPackage.get(aspirePackage);
  if (!href) return 'other';
  const segments = href.split('/').filter(Boolean);
  const start = segments.indexOf('integrations');
  if (start === -1) return 'other';
  let key = segments[start + 1];
  // Cloud integrations nest under a provider (`cloud/azure/...`); group by the
  // provider so the heading reads "Azure emulators" rather than "Cloud".
  if (key === 'cloud' && segments[start + 2]) {
    key = segments[start + 2];
  }
  return key ?? 'other';
}

/** A category group of container images for the reference catalog. */
export interface ContainerImageCategory {
  /** Stable key, usable as a heading anchor id (e.g. `databases`). */
  key: string;
  /** Human-friendly heading (e.g. `Databases`). */
  label: string;
  /** Images in this category, preserving the data file's package/primary order. */
  images: ContainerImage[];
}

/**
 * Group every container image into ordered categories for the reference catalog.
 * Categories follow the site's integration IA and a curated display order;
 * unknown categories are appended alphabetically with a title-cased label.
 */
export function getContainerImageCatalog(): ContainerImageCategory[] {
  const groups = new Map<string, ContainerImage[]>();
  for (const image of containerImages) {
    const key = categoryKeyFor(image.aspirePackage);
    const bucket = groups.get(key);
    if (bucket) {
      bucket.push(image);
    } else {
      groups.set(key, [image]);
    }
  }

  const orderIndex = (key: string) => {
    const index = CATEGORY_ORDER.indexOf(key);
    return index === -1 ? CATEGORY_ORDER.length : index;
  };

  return [...groups.entries()]
    .sort(([a], [b]) => orderIndex(a) - orderIndex(b) || a.localeCompare(b))
    .map(([key, images]) => ({
      key,
      label: CATEGORY_LABELS[key] ?? titleCase(key),
      images,
    }));
}
