allowBuilds:
  esbuild: true
  sharp: true

onlyBuiltDependencies:
  - esbuild
  - sharp

overrides:
  '@anthropic-ai/claude-code@<2.0.31': '>=2.0.31'
  ajv@<6.14.0: 6.14.0
  ajv@>=7.0.0-alpha.0 <8.18.0: 8.18.0
  brace-expansion@<5.0.6: '>=5.0.6'
  devalue@<5.6.4: '>=5.6.4'
  dompurify@<3.4.11: '>=3.4.11'
  esbuild@<0.28.1: '>=0.28.1'
  fast-xml-builder@<1.1.7: '>=1.1.7'
  fast-xml-parser@<5.7.0: '>=5.7.0'
  flatted@<3.4.2: '>=3.4.2'
  h3@<1.15.9: '>=1.15.9'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  minimatch@<10.2.3: '>=10.2.3'
  postcss@<8.5.10: '>=8.5.10'
  rollup@>=4.0.0 <4.59.0: '>=4.59.0'
  seroval: '>=1.4.1'
  simple-git@<3.36.0: '>=3.36.0'
  svgo@=4.0.0: '>=4.0.1'
  uuid@<14.0.0: '>=14.0.0'

patchedDependencies:
  starlight-llms-txt@0.8.1: patches/starlight-llms-txt@0.8.1.patch
