import type { StarlightSidebarTopicsUserConfig } from "starlight-sidebar-topics";

export const sidebarTopics: StarlightSidebarTopicsUserConfig = [
  {
    label: {
      da: 'Dokumenter',
      de: 'Dokumente',
      en: 'Docs',
      es: 'Documentos',
      fr: 'Documents',
      hi: 'दस्तावेज़',
      id: 'Dokumen',
      it: 'Documenti',
      ja: 'ドキュメント',
      ko: '문서',
      'pt-BR': 'Documentos',
      'pt-PT': 'Documentos',
      ru: 'Документы',
      tr: 'Belgeler',
      uk: 'Документи',
      'zh-CN': '文档',
    },
    link: 'get-started/welcome',
    icon: 'open-book',
    items: [
      {
        label: 'Welcome to Aspire', translations: {
          da: 'Velkommen til Aspire',
          de: 'Willkommen bei Aspire',
          en: 'Welcome to Aspire',
          es: 'Bienvenido a Aspire',
          fr: 'Bienvenue à Aspire',
          hi: 'Aspire में आपका स्वागत है',
          id: 'Selamat datang di Aspire',
          it: 'Benvenuto in Aspire',
          ja: 'Aspire へようこそ',
          ko: 'Aspire에 오신 것을 환영합니다',
          'pt-BR': 'Bem-vindo ao Aspire',
          'pt-PT': 'Bem-vindo ao Aspire',
          ru: 'Добро пожаловать в Aspire',
          tr: 'Aspire\'a Hoş Geldiniz',
          uk: 'Ласкаво просимо до Aspire',
          'zh-CN': '欢迎使用 Aspire',
        }, slug: 'get-started/welcome'
      },
      {
        label: "What's new", collapsed: true, items: [
          { label: 'Aspire 9.5', slug: 'whats-new/aspire-9-5' }
        ],
        translations: {
          da: 'Hvad er nyt',
          de: 'Was gibt es Neues',
          en: "What's new",
          es: 'Novedades',
          fr: 'Quoi de neuf',
          hi: 'क्या नया है',
          id: 'Apa yang baru',
          it: 'Novità',
          ja: '新着情報',
          ko: '새로운 소식',
          'pt-BR': 'Novidades',
          'pt-PT': 'Novidades',
          ru: 'Что нового',
          tr: 'Yeni neler var',
          uk: 'Що нового',
          'zh-CN': '新内容',
        }
      },
      {
        label: 'Get started', translations: {
          da: 'Kom godt i gang',
          de: 'Erste schritte',
          en: 'Get started',
          es: 'Empezar',
          fr: 'Commencer',
          hi: 'शुरू करें',
          id: 'Mulai',
          it: 'Iniziare',
          ja: '始める',
          ko: '시작하기',
          'pt-BR': 'Começar',
          'pt-PT': 'Começar',
          ru: 'Начать',
          tr: 'Başlamak',
          uk: 'Розпочати',
          'zh-CN': '开始',
        },
        items: [
          {
            label: 'Prerequisites',
            translations: {
              da: 'Forudsætninger',
              de: 'Voraussetzungen',
              en: 'Prerequisites',
              es: 'Requisitos previos',
              fr: 'Prérequis',
              hi: 'पूर्वापेक्षाएँ',
              id: 'Prasyarat',
              it: 'Prerequisiti',
              ja: '前提条件',
              ko: '전제 조건',
              'pt-BR': 'Pré-requisitos',
              'pt-PT': 'Pré-requisitos',
              ru: 'Предварительные требования',
              tr: 'Ön koşullar',
              uk: 'Попередні вимоги',
              'zh-CN': '先决条件',
            },
            slug: 'get-started/prerequisites'
          },
          {
            label: 'Install CLI',
            translations: {
              da: 'Installer CLI',
              de: 'CLI installieren',
              en: 'Install CLI',
              es: 'Instalar CLI',
              fr: 'Installer CLI',
              hi: 'CLI इंस्टॉल करें',
              id: 'Instal CLI',
              it: 'Installa CLI',
              ja: 'CLI をインストール',
              ko: 'CLI 설치',
              'pt-BR': 'Instalar CLI',
              'pt-PT': 'Instalar CLI',
              ru: 'Установить CLI',
              tr: 'CLI Kur',
              uk: 'Встановити CLI',
              'zh-CN': '安装 CLI',
            },
            slug: 'get-started/install-cli'
          },
          {
            label: 'Build your first app',
            translations: {
              da: 'Byg din første app',
              de: 'Erstellen Sie Ihre erste App',
              en: 'Build your first app',
              es: 'Construye tu primera app',
              fr: 'Construisez votre première application',
              hi: 'अपना पहला ऐप बनाएं',
              id: 'Bangun aplikasi pertama Anda',
              it: 'Crea la tua prima app',
              ja: '最初のアプリを作成',
              ko: '첫 번째 앱 만들기',
              'pt-BR': 'Construa seu primeiro app',
              'pt-PT': 'Construa a sua primeira app',
              ru: 'Создайте свое первое приложение',
              tr: 'İlk uygulamanızı oluşturun',
              uk: 'Створіть свій перший додаток',
              'zh-CN': '构建您的第一个应用',
            },
            slug: 'get-started/first-app',
            badge: {
              text: {
                da: 'Hurtigstart',
                de: 'Schnellstart',
                en: 'Quickstart',
                es: 'Inicio rápido',
                fr: 'Démarrage rapide',
                hi: 'त्वरित प्रारंभ',
                id: 'Panduan Cepat',
                it: 'Avvio rapido',
                ja: 'クイックスタート',
                ko: '빠른 시작',
                'pt-BR': 'Introdução Rápida',
                'pt-PT': 'Introdução Rápida',
                ru: 'Быстрый старт',
                tr: 'Hızlı Başlangıç',
                uk: 'Швидкий старт',
                'zh-CN': '快速入门',
              }
            }
          }
        ]
      },
      {
        label: 'Concepts',
        translations: {
          da: 'Begreber',
          de: 'Konzepte',
          en: 'Concepts',
          es: 'Conceptos',
          fr: 'Concepts',
          hi: 'अवधारणाएँ',
          id: 'Konsep',
          it: 'Concetti',
          ja: '概念',
          ko: '개념',
          'pt-BR': 'Conceitos',
          'pt-PT': 'Conceitos',
          ru: 'Концепции',
          tr: 'Kavramlar',
          uk: 'Концепції',
          'zh-CN': '概念',
        },
        items: [
          {
            label: 'What is Aspire?', translations: {
              da: 'Hvad er Aspire?',
              de: 'Was ist Aspire?',
              en: 'What is Aspire?',
              es: '¿Qué es Aspire?',
              fr: 'Qu’est-ce qu’Aspire ?',
              hi: 'Aspire क्या है?',
              id: 'Apa itu Aspire?',
              it: 'Che cos’è Aspire?',
              ja: 'Aspire とは何ですか?',
              ko: 'Aspire란 무엇인가요?',
              'pt-BR': 'O que é Aspire?',
              'pt-PT': 'O que é Aspire?',
              ru: 'Что такое Aspire?',
              tr: 'Aspire nedir?',
              uk: 'Що таке Aspire?',
              'zh-CN': 'Aspire 是什么？',
            }, slug: 'get-started/what-is-aspire'
          },
          {
            label: 'What is the AppHost?', translations: {
              da: 'Hvad er AppHost?',
              de: 'Was ist der AppHost?',
              en: 'What is the AppHost?',
              es: '¿Qué es el AppHost?',
              fr: 'Qu\'est-ce que l’AppHost ?',
              hi: 'AppHost क्या है?',
              id: 'Apa itu AppHost?',
              it: 'Che cos\'è l’AppHost?',
              ja: 'AppHost とは?',
              ko: 'AppHost란 무엇인가요?',
              'pt-BR': 'O que é o AppHost?',
              'pt-PT': 'O que é o AppHost?',
              ru: 'Что такое AppHost?',
              tr: 'AppHost nedir?',
              uk: 'Що таке AppHost?',
              'zh-CN': '什么是 AppHost？',
            }, slug: 'get-started/app-host'
          },
          {
            label: 'Understanding resources', translations: {
              da: 'Forstå ressourcer',
              de: 'Ressourcen verstehen',
              en: 'Understanding resources',
              es: 'Comprender los recursos',
              fr: 'Comprendre les ressources',
              hi: 'संसाधनों को समझना',
              id: 'Memahami Sumber Daya',
              it: 'Comprendere le risorse',
              ja: 'リソースの理解',
              ko: '리소스 이해',
              'pt-BR': 'Compreendendo os recursos',
              'pt-PT': 'Compreender os recursos',
              ru: 'Понимание ресурсов',
              tr: 'Kaynakları anlama',
              uk: 'Розуміння ресурсів',
              'zh-CN': '了解资源',
            }, slug: 'get-started/resources'
          },
          {
            label: 'Deployment and app topology', translations: {
              da: 'Udrulning og apptopologi',
              de: 'Bereitstellung und app-topologie',
              en: 'Deployment and app topology',
              es: 'Despliegue y topología de la aplicación',
              fr: 'Déploiement et topologie de l’application',
              hi: 'परिनियोजन और ऐप टोपोलॉजी',
              id: 'Penyebaran dan topologi aplikasi',
              it: 'Distribuzione e topologia dell’applicazione',
              ja: 'デプロイとアプリのトポロジ',
              ko: '배포 및 앱 토폴로지',
              'pt-BR': 'Implantação e topologia do aplicativo',
              'pt-PT': 'Implementação e topologia da aplicação',
              ru: 'Развертывание и топология приложения',
              tr: 'Dağıtım ve uygulama topolojisi',
              uk: 'Розгортання і топологія застосунку',
              'zh-CN': '部署与应用拓扑',
            }, slug: 'get-started/deployment'
          }
        ]
      },
      {
        label: 'Architecture', translations: {
          da: 'Arkitektur',
          de: 'Architektur',
          en: 'Architecture',
          es: 'Arquitectura',
          fr: 'Architecture',
          hi: 'आर्किटेक्चर',
          id: 'Arsitektur',
          it: 'Architettura',
          ja: 'アーキテクチャ',
          ko: '아키텍처',
          'pt-BR': 'Arquitetura',
          'pt-PT': 'Arquitetura',
          ru: 'Архитектура',
          tr: 'Mimari',
          uk: 'Архітектура',
          'zh-CN': '架构',
        },
        collapsed: true,
        items: [
          {
            label: 'Overview',
            translations: {
              da: 'Oversigt',
              de: 'Übersicht',
              en: 'Overview',
              es: 'Descripción general',
              fr: 'Vue d\'ensemble',
              hi: 'अवलोकन',
              id: 'Ikhtisar',
              it: 'Panoramica',
              ja: '概要',
              ko: '개요',
              pt: 'Visão geral',
              'pt-BR': 'Visão geral',
              'pt-PT': 'Visão geral',
              ru: 'Обзор',
              tr: 'Genel Bakış',
              uk: 'Огляд',
              'zh-CN': '概述',
            },
            slug: 'architecture/overview'
          },
          {
            label: 'Resource model', translations: {
              da: 'Ressourcemodel',
              de: 'Ressourcenmodell',
              en: 'Resource model',
              es: 'Modelo de recurso',
              fr: 'Modèle de ressource',
              hi: 'संसाधन मॉडल',
              id: 'Model Sumber Daya',
              it: 'Modello di risorsa',
              ja: 'リソースモデル',
              ko: '리소스 모델',
              'pt-BR': 'Modelo de Recurso',
              'pt-PT': 'Modelo de Recurso',
              ru: 'Модель ресурса',
              tr: 'Kaynak Modeli',
              uk: 'Модель ресурсу',
              'zh-CN': '资源模型',
            }, slug: 'architecture/resource-model'
          },
          {
            label: 'Resource hierarchies',
            translations: {
              da: 'Ressourcehierarkier',
              de: 'Ressourcenhierarchien',
              en: 'Resource hierarchies',
              es: 'Jerarquías de recursos',
              fr: 'Hiérarchies de ressources',
              hi: 'संसाधन पदानुक्रम',
              id: 'Hierarki Sumber Daya',
              it: 'Gerarchie delle risorse',
              ja: 'リソース階層',
              ko: '리소스 계층',
              'pt-BR': 'Hierarquias de Recursos',
              'pt-PT': 'Hierarquias de Recursos',
              ru: 'Иерархии ресурсов',
              tr: 'Kaynak Hiyerarşileri',
              uk: 'Ієрархії ресурсів',
              'zh-CN': '资源层次结构',
            }, slug: 'architecture/resource-hierarchies'
          },
          {
            label: 'Resource API patterns',
            translations: {
              da: 'Ressource-API-mønstre',
              de: 'Ressource-API-Muster',
              en: 'Resource API patterns',
              es: 'Patrones de API de recursos',
              fr: 'Modèles d\'API de ressources',
              hi: 'संसाधन एपीआई पैटर्न',
              id: 'Pola API Sumber Daya',
              it: 'Modelli di API di risorse',
              ja: 'リソースAPIパターン',
              ko: '리소스 API 패턴',
              'pt-BR': 'Padrões de API de Recursos',
              'pt-PT': 'Padrões de API de Recursos',
              ru: 'Шаблоны API ресурсов',
              tr: 'Kaynak API Desenleri',
              uk: 'Шаблони API ресурсів',
              'zh-CN': '资源API模式',
            }, slug: 'architecture/resource-api-patterns'
          },
          {
            label: 'Resource publishing',
            translations: {
              da: 'Ressourcepublicering',
              de: 'Ressourcenveröffentlichung',
              en: 'Resource publishing',
              es: 'Publicación de recursos',
              fr: 'Publication de ressources',
              hi: 'संसाधन प्रकाशन',
              id: 'Penerbitan Sumber Daya',
              it: 'Pubblicazione delle risorse',
              ja: 'リソースの公開',
              ko: '리소스 게시',
              'pt-BR': 'Publicação de Recursos',
              'pt-PT': 'Publicação de Recursos',
              ru: 'Публикация ресурсов',
              tr: 'Kaynak Yayınlama',
              uk: 'Публікація ресурсів',
              'zh-CN': '资源发布',
            },
            slug: 'architecture/resource-publishing'
          },
          {
            label: 'Resource examples', translations: {
              da: 'Ressourceeksempler',
              de: 'Ressourcenbeispiele',
              en: 'Resource examples',
              es: 'Ejemplos de recursos',
              fr: 'Exemples de ressources',
              hi: 'संसाधन उदाहरण',
              id: 'Contoh Sumber Daya',
              it: 'Esempi di risorse',
              ja: 'リソースの例',
              ko: '리소스 예제',
              'pt-BR': 'Exemplos de Recursos',
              'pt-PT': 'Exemplos de Recursos',
              ru: 'Примеры ресурсов',
              tr: 'Kaynak Örnekleri',
              uk: 'Приклади ресурсів',
              'zh-CN': '资源示例',
            }, slug: 'architecture/resource-examples'
          },
          {
            label: 'Glossary', translations: {
              da: 'Ordbog',
              de: 'Glossar',
              en: 'Glossary',
              es: 'Glosario',
              fr: 'Glossaire',
              hi: 'शब्दावली',
              id: 'Kamus',
              it: 'Glossario',
              ja: '用語集',
              ko: '용어집',
              'pt-BR': 'Glossário',
              'pt-PT': 'Glossário',
              ru: 'Глоссарий',
              tr: 'Sözlük',
              uk: 'Глосарій',
              'zh-CN': '术语表',
            },
            slug: 'architecture/glossary'
          },
        ]
      }
    ]
  },
  {
    label: {
      en: 'Integrations',
      es: 'Integraciones',
      fr: 'Intégrations',
      de: 'Integrationen',
      it: 'Integrazioni',
      pt: 'Integrações',
      ru: 'Интеграции',
      'zh-CN': '集成',
      da: 'Integrationer',
      hi: 'इंटीग्रेशन',
      id: 'Integrasi',
      ja: 'インテグレーション',
      ko: '통합',
      'pt-BR': 'Integrações',
      'pt-PT': 'Integrações',
      tr: 'Entegrasyonlar',
      uk: 'Інтеграції',
    },
    link: '/integrations/gallery',
    icon: 'puzzle',
    items: [
      {
        label: 'Explore', translations: {
          da: 'Udforsk',
          de: 'Entdecken',
          en: 'Explore',
          es: 'Explorar',
          fr: 'Explorer',
          hi: 'अन्वेषण',
          id: 'Jelajahi',
          it: 'Esplora',
          ja: '参照',
          ko: '탐색',
          pt: 'Explorar',
          'pt-BR': 'Explorar',
          'pt-PT': 'Explorar',
          ru: 'Исследовать',
          tr: 'Keşfet',
          uk: 'Дослідити',
          'zh-CN': '探索',
        }, items: [
          {
            label: 'Integration gallery', translations: {
              da: 'Integrationsgalleri',
              de: 'Integrationsgalerie',
              en: 'Integration gallery',
              es: 'Galería de integraciones',
              fr: 'Galerie d’intégrations',
              hi: 'इंटीग्रेशन गैलरी',
              id: 'Galeri integrasi',
              it: 'Galleria delle integrazioni',
              ja: 'インテグレーションギャラリー',
              ko: '통합 갤러리',
              pt: 'Galeria de integrações',
              'pt-BR': 'Galeria de integrações',
              'pt-PT': 'Galeria de integrações',
              ru: 'Галерея интеграций',
              tr: 'Entegrasyon galerisi',
              uk: 'Галерея інтеграцій',
              'zh-CN': '集成图库',
            }, slug: 'integrations/gallery'
          },
          {
            label: 'Overview', translations: {
              da: 'Oversigt',
              de: 'Übersicht',
              en: 'Overview',
              es: 'Descripción general',
              fr: 'Vue d\'ensemble',
              hi: 'अवलोकन',
              id: 'Ikhtisar',
              it: 'Panoramica',
              ja: '概要',
              ko: '개요',
              pt: 'Visão geral',
              'pt-BR': 'Visão geral',
              'pt-PT': 'Visão geral',
              ru: 'Обзор',
              tr: 'Genel Bakış',
              uk: 'Огляд',
              'zh-CN': '概述',
            }, slug: 'integrations/overview'
          },
        ]
      },
      {
        label: 'Database',
        translations: {
          da: 'Database',
          de: 'Datenbank',
          en: 'Database',
          es: 'Base de datos',
          fr: 'Base de données',
          hi: 'डेटाबेस',
          id: 'Basis Data',
          it: 'Database',
          ja: 'データベース',
          ko: '데이터베이스',
          pt: 'Banco de dados',
          'pt-BR': 'Banco de dados',
          'pt-PT': 'Base de dados',
          ru: 'База данных',
          tr: 'Veritabanı',
          uk: 'База даних',
          'zh-CN': '数据库',
        }, items: [
          { label: 'PostgreSQL', slug: 'integrations/postgres' },
        ]
      },
      {
        label: 'Messaging',
        translations: {
          da: 'Meddelelser',
          de: 'Messaging',
          en: 'Messaging',
          es: 'Mensajería',
          fr: 'Messagerie',
          hi: 'मैसेजिंग',
          id: 'Pengiriman Pesan',
          it: 'Messaggistica',
          ja: 'メッセージング',
          ko: '메시징',
          pt: 'Mensageria',
          'pt-BR': 'Mensageria',
          'pt-PT': 'Mensageria',
          ru: 'Обмен сообщениями',
          tr: 'Mesajlaşma',
          uk: 'Обмін повідомленнями',
          'zh-CN': '消息传递',
        },
        items: [
          { label: 'RabbitMQ', slug: 'integrations/rabbitmq' },
        ]
      }
    ],
  },
  {
    label: {
      en: 'Dashboard',
      es: 'Panel',
      fr: 'Tableau de bord',
      de: 'Dashboard',
      it: 'Dashboard',
      pt: 'Painel',
      ru: 'Панель управления',
      'zh-CN': '仪表板',
      da: 'Dashboard',
      hi: 'डैशबोर्ड',
      id: 'Dasbor',
      ja: 'ダッシュボード',
      ko: '대시보드',
      'pt-BR': 'Painel',
      'pt-PT': 'Painel',
      tr: 'Gösterge Paneli',
      uk: 'Панель керування',
    },
    link: '/dashboard/overview',
    icon: 'seti:happenings',
    items: [
      {
        label: 'Overview', translations: {
          da: 'Oversigt',
          de: 'Übersicht',
          en: 'Overview',
          es: 'Descripción general',
          fr: 'Vue d\'ensemble',
          hi: 'अवलोकन',
          id: 'Ikhtisar',
          it: 'Panoramica',
          ja: '概要',
          ko: '개요',
          pt: 'Visão geral',
          'pt-BR': 'Visão geral',
          'pt-PT': 'Visão geral',
          ru: 'Обзор',
          tr: 'Genel Bakış',
          uk: 'Огляд',
          'zh-CN': '概述',
        }, slug: 'dashboard/overview'
      },
      {
        label: 'Explore features', translations: {
          da: 'Udforsk funktioner',
          de: 'Funktionen erkunden',
          en: 'Explore features',
          es: 'Explorar funciones',
          fr: 'Explorer les fonctionnalités',
          hi: 'विशेषताएँ एक्सप्लोर करें',
          id: 'Jelajahi fitur',
          it: 'Esplora funzionalità',
          ja: '機能を探る',
          ko: '기능 탐색',
          pt: 'Explorar recursos',
          'pt-BR': 'Explorar recursos',
          'pt-PT': 'Explorar recursos',
          ru: 'Изучение функций',
          tr: 'Özellikleri keşfet',
          uk: 'Дослідити функції',
          'zh-CN': '探索功能',
        }, slug: 'dashboard/explore'
      },
      {
        label: 'GitHub Copilot', slug: 'dashboard/copilot'
      },
      {
        label: 'Aspire MCP server', translations: {
          da: 'Aspire MCP-server',
          de: 'Aspire MCP-Server',
          en: 'Aspire MCP server',
          es: 'Servidor Aspire MCP',
          fr: 'Serveur Aspire MCP',
          hi: 'Aspire MCP सर्वर',
          id: 'Server Aspire MCP',
          it: 'Server Aspire MCP',
          ja: 'Aspire MCPサーバー',
          ko: 'Aspire MCP 서버',
          pt: 'Servidor Aspire MCP',
          'pt-BR': 'Servidor Aspire MCP',
          'pt-PT': 'Servidor Aspire MCP',
          ru: 'Сервер Aspire MCP',
          tr: 'Aspire MCP sunucusu',
          uk: 'Сервер Aspire MCP',
          'zh-CN': 'Aspire MCP 服务器',
        }, slug: 'dashboard/mcp-server'
      },
      {
        label: 'Standalone mode', translations: {
          da: 'Selvstændig tilstand',
          de: 'Eigenständiger Modus',
          en: 'Standalone mode',
          es: 'Modo independiente',
          fr: 'Mode autonome',
          hi: 'स्टैंडअलोन मोड',
          id: 'Mode mandiri',
          it: 'Modalità autonoma',
          ja: 'スタンドアロンモード',
          ko: '독립 실행 모드',
          pt: 'Modo autônomo',
          'pt-BR': 'Modo autônomo',
          'pt-PT': 'Modo autónomo',
          ru: 'Автономный режим',
          tr: 'Bağımsız mod',
          uk: 'Автономний режим',
          'zh-CN': '独立模式',
        }, items: [
          { label: 'Overview', slug: 'dashboard/standalone' },
          { label: 'Node.js apps', slug: 'dashboard/standalone-for-nodejs', badge: { text: 'Tutorial', variant: 'success' } },
          { label: 'Python apps', slug: 'dashboard/standalone-for-python', badge: { text: 'Tutorial', variant: 'success' } },
        ]
      },
      {
        label: 'Configuration', translations: {
          da: 'Konfiguration',
          de: 'Konfiguration',
          en: 'Configuration',
          es: 'Configuración',
          fr: 'Configuration',
          hi: 'कॉन्फ़िगरेशन',
          id: 'Konfigurasi',
          it: 'Configurazione',
          ja: '構成',
          ko: '구성',
          pt: 'Configuração',
          'pt-BR': 'Configuração',
          'pt-PT': 'Configuração',
          ru: 'Конфигурация',
          tr: 'Yapılandırma',
          uk: 'Конфігурація',
          'zh-CN': '配置',
        }, slug: 'dashboard/configuration'
      },
      {
        label: 'Security considerations', translations: {
          da: 'Sikkerhedsovervejelser',
          de: 'Sicherheitsüberlegungen',
          en: 'Security considerations',
          es: 'Consideraciones de seguridad',
          fr: 'Considérations de sécurité',
          hi: 'सुरक्षा संबंधी विचार',
          id: 'Pertimbangan keamanan',
          it: 'Considerazioni sulla sicurezza',
          ja: 'セキュリティに関する考慮事項',
          ko: '보안 고려 사항',
          pt: 'Considerações de segurança',
          'pt-BR': 'Considerações de segurança',
          'pt-PT': 'Considerações de segurança',
          ru: 'Соображения безопасности',
          tr: 'Güvenlik değerlendirmeleri',
          uk: 'Міркування щодо безпеки',
          'zh-CN': '安全注意事项',
        }, slug: 'dashboard/security-considerations'
      },
      {
        label: 'Enable browser telemetry', translations: {
          da: 'Aktivér browsertelemetri',
          de: 'Browser-Telemetrie aktivieren',
          en: 'Enable browser telemetry',
          es: 'Habilitar telemetría del navegador',
          fr: 'Activer la télémétrie du navigateur',
          hi: 'ब्राउज़र टेलीमेट्री सक्षम करें',
          id: 'Aktifkan telemetri browser',
          it: 'Abilita telemetria del browser',
          ja: 'ブラウザのテレメトリを有効にする',
          ko: '브라우저 원격 분석 활성화',
          pt: 'Ativar telemetria do navegador',
          'pt-BR': 'Ativar telemetria do navegador',
          'pt-PT': 'Ativar telemetria do navegador',
          ru: 'Включить телеметрию браузера',
          tr: 'Tarayıcı telemetrisi etkinleştirme',
          uk: 'Увімкнути телеметрію браузера',
          'zh-CN': '启用浏览器遥测',
        },
        slug: 'dashboard/enable-browser-telemetry'
      },
      {
        label: 'Microsoft telemetry', translations: {
          da: 'Microsoft telemetri',
          de: 'Microsoft-Telemetrie',
          en: 'Microsoft telemetry',
          es: 'Telemetría de Microsoft',
          fr: 'Télémétrie Microsoft',
          hi: 'Microsoft टेलीमेट्री',
          id: 'Telemetri Microsoft',
          it: 'Telemetria Microsoft',
          ja: 'Microsoft テレメトリ',
          ko: 'Microsoft 원격 분석',
          pt: 'Telemetria da Microsoft',
          'pt-BR': 'Telemetria da Microsoft',
          'pt-PT': 'Telemetria da Microsoft',
          ru: 'Телеметрия Microsoft',
          tr: 'Microsoft telemetrisi',
          uk: 'Телеметрія Microsoft',
          'zh-CN': 'Microsoft 遥测',
        }, slug: 'dashboard/microsoft-collected-dashboard-telemetry'
      }
    ]
  },
  {
    label: {
      en: 'CLI Reference',
      es: 'Referencia de CLI',
      fr: 'Référence CLI',
      de: 'CLI-Referenz',
      it: 'Riferimento CLI',
      pt: 'Referência de CLI',
      ru: 'Справочник CLI',
      'zh-CN': 'CLI 参考',
      da: 'CLI-reference',
      hi: 'CLI संदर्भ',
      id: 'Referensi CLI',
      ja: 'CLI リファレンス',
      ko: 'CLI 참고서',
      'pt-BR': 'Referência de CLI',
      'pt-PT': 'Referência de CLI',
      tr: 'CLI Referansı',
      uk: 'CLI Довідник',
    },
    link: '/reference/cli/overview',
    icon: 'forward-slash',
    items: [
      {
        label: 'Overview', translations: {
          da: 'Oversigt', de: 'Übersicht', en: 'Overview', es: 'Descripción general', fr: 'Vue d\'ensemble', hi: 'अवलोकन', id: 'Ikhtisar', it: 'Panoramica', ja: '概要', ko: '개요', pt: 'Visão geral', 'pt-BR': 'Visão geral', 'pt-PT': 'Visão geral', ru: 'Обзор', tr: 'Genel Bakış', uk: 'Огляд', 'zh-CN': '概述'
        }, slug: 'reference/cli/overview'
      },
      {
        label: 'Install script', translations: {
          da: 'Installationsscript', de: 'Installationsskript', en: 'Install script', es: 'Script de instalación', fr: 'Script d\'installation', hi: 'इंस्टॉलेशन स्क्रिप्ट', id: 'Skrip Instalasi', it: 'Script di installazione', ja: 'インストールスクリプト', ko: '설치 스크립트', pt: 'Script de instalação', 'pt-BR': 'Script de instalação', 'pt-PT': 'Script de instalação', ru: 'Скрипт установки', tr: 'Kurulum Betiği', uk: 'Скрипт установки', 'zh-CN': '安装脚本'
        }, slug: 'reference/cli/install-script'
      },
      {
        label: 'Configuration', translations: {
          da: 'Konfiguration', de: 'Konfiguration', en: 'Configuration', es: 'Configuración', fr: 'Configuration', hi: 'कॉन्फ़िगरेशन', id: 'Konfigurasi', it: 'Configurazione', ja: '構成', ko: '구성', pt: 'Configuração', 'pt-BR': 'Configuração', 'pt-PT': 'Configuração', ru: 'Конфигурация', tr: 'Yapılandırma', uk: 'Конфігурація', 'zh-CN': '配置'
        }, slug: 'reference/cli/configuration'
      },
      {
        label: 'Commands', translations: {
          da: 'Kommandoer', de: 'Befehle', en: 'Commands', es: 'Comandos', fr: 'Commandes', hi: 'कमांड', id: 'Perintah', it: 'Comandi', ja: 'コマンド', ko: '명령어', pt: 'Comandos', 'pt-BR': 'Comandos', 'pt-PT': 'Comandos', ru: 'Команды', tr: 'Komutlar', uk: 'Команди', 'zh-CN': '命令'
        }, items: [
          { label: 'aspire', slug: 'reference/cli/commands/aspire' },
          { label: 'aspire add', slug: 'reference/cli/commands/aspire-add' },
          {
            label: 'aspire cache', collapsed: true, items: [
              { label: 'aspire cache', slug: 'reference/cli/commands/aspire-cache' },
              { label: 'aspire cache clear', slug: 'reference/cli/commands/aspire-cache-clear' },
            ]
          },
          {
            label: 'aspire config', collapsed: true, items: [
              { label: 'aspire config', slug: 'reference/cli/commands/aspire-config' },
              { label: 'aspire config list', slug: 'reference/cli/commands/aspire-config-list' },
              { label: 'aspire config get', slug: 'reference/cli/commands/aspire-config-get' },
              { label: 'aspire config set', slug: 'reference/cli/commands/aspire-config-set' },
              { label: 'aspire config delete', slug: 'reference/cli/commands/aspire-config-delete' },
            ]
          },
          { label: 'aspire deploy', slug: 'reference/cli/commands/aspire-deploy' },
          { label: 'aspire do', slug: 'reference/cli/commands/aspire-do' },
          { label: 'aspire exec', slug: 'reference/cli/commands/aspire-exec' },
          { label: 'aspire init', slug: 'reference/cli/commands/aspire-init' },
          { label: 'aspire new', slug: 'reference/cli/commands/aspire-new' },
          { label: 'aspire publish', slug: 'reference/cli/commands/aspire-publish' },
          { label: 'aspire run', slug: 'reference/cli/commands/aspire-run' },
          { label: 'aspire update', slug: 'reference/cli/commands/aspire-update' },
        ]
      }
    ]
  },
  // {
  //     label: 'API Reference',
  //     id: 'reference-api',
  //     link: '/api',
  //     icon: 'document',
  //     items: [
  //         { 
  //             label: 'API Reference', 
  //             collapsed: false, 
  //             autogenerate: { directory: '/reference/api', collapsed: true }
  //         },
  //     ]
  // },
  {
    label: {
      en: 'Community',
      es: 'Comunidad',
      fr: 'Communauté',
      de: 'Gemeinschaft',
      it: 'Comunità',
      pt: 'Comunidade',
      ru: 'Сообщество',
      'zh-CN': '社区',
      da: 'Fællesskab',
      hi: 'समुदाय',
      id: 'Komunitas',
      ja: 'コミュニティ',
      ko: '커뮤니티',
      'pt-BR': 'Comunidade',
      'pt-PT': 'Comunidade',
      tr: 'Topluluk',
      uk: 'Спільнота',
    },
    link: '/community/contributors',
    icon: 'heart',
    items: [
      {
        label: 'Contributors', translations: {
          da: 'Bidragydere',
          de: 'Mitwirkende',
          en: 'Contributors',
          es: 'Colaboradores',
          fr: 'Contributeurs',
          hi: 'योगदानकर्ता',
          id: 'Kontributor',
          it: 'Collaboratori',
          ja: 'コントリビューター',
          ko: '기여자',
          pt: 'Contribuidores',
          'pt-BR': 'Contribuidores',
          'pt-PT': 'Contribuidores',
          ru: 'Участники',
          tr: 'Katkıda Bulunanlar',
          uk: 'Учасники',
          'zh-CN': '贡献者'
        }, slug: 'community/contributors'
      },
      {
        label: 'BlueSky',
        slug: 'community/posts',
        badge: {
          text: '#aspire',
          variant: 'note'
        }
      },
      {
        label: 'Videos', translations: {
          da: 'Videoer',
          de: 'Videos',
          en: 'Videos',
          es: 'Videos',
          fr: 'Vidéos',
          hi: 'वीडियो',
          id: 'Video',
          it: 'Video',
          ja: '動画',
          ko: '비디오',
          pt: 'Vídeos',
          'pt-BR': 'Vídeos',
          'pt-PT': 'Vídeos',
          ru: 'Видео',
          tr: 'Videolar',
          uk: 'Відео',
          'zh-CN': '视频'
        }, slug: 'community/videos'
      },
    ]
  },
  {
    label: {
      en: 'Samples',
      es: 'Ejemplos',
      fr: 'Exemples',
      de: 'Beispiele',
      it: 'Esempi',
      pt: 'Exemplos',
      ru: 'Примеры',
      'zh-CN': '示例',
      da: 'Eksempler',
      hi: 'उदाहरण',
      id: 'Contoh',
      ja: 'サンプル',
      ko: '샘플',
      'pt-BR': 'Exemplos',
      'pt-PT': 'Exemplos',
      tr: 'Örnekler',
      uk: 'Приклади',
    },
    link: 'https://aka.ms/aspiresamples',
    icon: 'vscode',
  },
];