import type { StarlightSidebarTopicsUserConfig } from 'starlight-sidebar-topics';

export const agenticTopics: StarlightSidebarTopicsUserConfig = {
  label: {
    en: 'Agentic development',
    es: 'Desarrollo con agentes',
    fr: 'Développement agentique',
    de: 'Agentengestützte Entwicklung',
    it: 'Sviluppo agentico',
    pt: 'Desenvolvimento agêntico',
    ru: 'Агентная разработка',
    'zh-CN': '代理开发',
    da: 'Agentudvikling',
    hi: 'एजेंट विकास',
    id: 'Pengembangan agen',
    ja: 'エージェント開発',
    ko: '에이전트 개발',
    'pt-BR': 'Desenvolvimento com agentes',
    'pt-PT': 'Desenvolvimento com agentes',
    tr: 'Ajans geliştirme',
    uk: 'Агентна розробка',
  },
  link: '/agentic/overview',
  icon: 'star',
  items: [
    {
      label: 'Overview',
      translations: {
        da: 'Oversigt',
        de: 'Übersicht',
        en: 'Overview',
        es: 'Descripción general',
        fr: "Vue d'ensemble",
        hi: 'अवलोकन',
        id: 'Ikhtisar',
        it: 'Panoramica',
        ja: '概要',
        ko: '개요',
        pt: 'Visão geral',
        'pt-BR': 'Visão geral',
        'pt-PT': 'Visão geral',
        ru: 'Обзор',
        tr: 'Genel Bakış',
        uk: 'Огляд',
        'zh-CN': '概述',
      },
      slug: 'agentic/overview',
    },
  ],
};
