import type { StarlightSidebarTopicsUserConfig } from 'starlight-sidebar-topics';

export const cliReferenceTopics: StarlightSidebarTopicsUserConfig = {
  label: {
    en: 'CLI Reference',
    es: 'Referencia de CLI',
    fr: 'Référence CLI',
    de: 'CLI-Referenz',
    it: 'Riferimento CLI',
    pt: 'Referência de CLI',
    ru: 'Справочник CLI',
    'zh-CN': 'CLI 参考',
    da: 'CLI-reference',
    hi: 'CLI संदर्भ',
    id: 'Referensi CLI',
    ja: 'CLI リファレンス',
    ko: 'CLI 참고서',
    'pt-BR': 'Referência de CLI',
    'pt-PT': 'Referência de CLI',
    tr: 'CLI Referansı',
    uk: 'CLI Довідник',
  },
  link: '/reference/cli/overview',
  icon: 'forward-slash',
  items: [
    {
      label: 'Overview',
      translations: {
        da: 'Oversigt',
        de: 'Übersicht',
        en: 'Overview',
        es: 'Descripción general',
        fr: "Vue d'ensemble",
        hi: 'अवलोकन',
        id: 'Ikhtisar',
        it: 'Panoramica',
        ja: '概要',
        ko: '개요',
        pt: 'Visão geral',
        'pt-BR': 'Visão geral',
        'pt-PT': 'Visão geral',
        ru: 'Обзор',
        tr: 'Genel Bakış',
        uk: 'Огляд',
        'zh-CN': '概述',
      },
      slug: 'reference/cli/overview',
    },
    {
      label: 'Install script',
      translations: {
        da: 'Installationsscript',
        de: 'Installationsskript',
        en: 'Install script',
        es: 'Script de instalación',
        fr: "Script d'installation",
        hi: 'इंस्टॉलेशन स्क्रिप्ट',
        id: 'Skrip Instalasi',
        it: 'Script di installazione',
        ja: 'インストールスクリプト',
        ko: '설치 스크립트',
        pt: 'Script de instalação',
        'pt-BR': 'Script de instalação',
        'pt-PT': 'Script de instalação',
        ru: 'Скрипт установки',
        tr: 'Kurulum Betiği',
        uk: 'Скрипт установки',
        'zh-CN': '安装脚本',
      },
      slug: 'reference/cli/install-script',
    },
    {
      label: 'Configuration',
      translations: {
        da: 'Konfiguration',
        de: 'Konfiguration',
        en: 'Configuration',
        es: 'Configuración',
        fr: 'Configuration',
        hi: 'कॉन्फ़िगरेशन',
        id: 'Konfigurasi',
        it: 'Configurazione',
        ja: '構成',
        ko: '구성',
        pt: 'Configuração',
        'pt-BR': 'Configuração',
        'pt-PT': 'Configuração',
        ru: 'Конфигурация',
        tr: 'Yapılandırma',
        uk: 'Конфігурація',
        'zh-CN': '配置',
      },
      slug: 'reference/cli/configuration',
    },
    {
      label: 'Commands',
      translations: {
        da: 'Kommandoer',
        de: 'Befehle',
        en: 'Commands',
        es: 'Comandos',
        fr: 'Commandes',
        hi: 'कमांड',
        id: 'Perintah',
        it: 'Comandi',
        ja: 'コマンド',
        ko: '명령어',
        pt: 'Comandos',
        'pt-BR': 'Comandos',
        'pt-PT': 'Comandos',
        ru: 'Команды',
        tr: 'Komutlar',
        uk: 'Команди',
        'zh-CN': '命令',
      },
      items: [
        { label: 'aspire', slug: 'reference/cli/commands/aspire' },
        { label: 'aspire add', slug: 'reference/cli/commands/aspire-add' },
        {
          label: 'aspire cache',
          collapsed: true,
          items: [
            {
              label: 'aspire cache',
              slug: 'reference/cli/commands/aspire-cache',
            },
            {
              label: 'aspire cache clear',
              slug: 'reference/cli/commands/aspire-cache-clear',
            },
          ],
        },
        {
          label: 'aspire config',
          collapsed: true,
          items: [
            {
              label: 'aspire config',
              slug: 'reference/cli/commands/aspire-config',
            },
            {
              label: 'aspire config list',
              slug: 'reference/cli/commands/aspire-config-list',
            },
            {
              label: 'aspire config get',
              slug: 'reference/cli/commands/aspire-config-get',
            },
            {
              label: 'aspire config set',
              slug: 'reference/cli/commands/aspire-config-set',
            },
            {
              label: 'aspire config delete',
              slug: 'reference/cli/commands/aspire-config-delete',
            },
          ],
        },
        {
          label: 'aspire deploy',
          slug: 'reference/cli/commands/aspire-deploy',
        },
        { label: 'aspire do', slug: 'reference/cli/commands/aspire-do' },
        { label: 'aspire exec', slug: 'reference/cli/commands/aspire-exec' },
        { label: 'aspire init', slug: 'reference/cli/commands/aspire-init' },
        { label: 'aspire new', slug: 'reference/cli/commands/aspire-new' },
        {
          label: 'aspire publish',
          slug: 'reference/cli/commands/aspire-publish',
        },
        { label: 'aspire run', slug: 'reference/cli/commands/aspire-run' },
        {
          label: 'aspire update',
          slug: 'reference/cli/commands/aspire-update',
        },
      ],
    },
  ],
};
