import type { StarlightSidebarTopicsUserConfig } from 'starlight-sidebar-topics';

export const communityTopics: StarlightSidebarTopicsUserConfig = {
  label: {
    en: 'Community',
    es: 'Comunidad',
    fr: 'Communauté',
    de: 'Gemeinschaft',
    it: 'Comunità',
    ru: 'Сообщество',
    'zh-CN': '社区',
    da: 'Fællesskab',
    hi: 'समुदाय',
    id: 'Komunitas',
    ja: 'コミュニティ',
    ko: '커뮤니티',
    'pt-BR': 'Comunidade',
    tr: 'Topluluk',
    uk: 'Спільнота',
  },
  link: '/community/',
  icon: 'heart',
  items: [
    {
      label: 'Aspire Community',
      translations: {
        da: 'Aspire-fællesskab',
        de: 'Aspire-Gemeinschaft',
        en: 'Aspire Community',
        es: 'Comunidad de Aspire',
        fr: 'Communauté Aspire',
        hi: 'Aspire समुदाय',
        id: 'Komunitas Aspire',
        it: 'Comunità di Aspire',
        ja: 'Aspireコミュニティ',
        ko: 'Aspire 커뮤니티',
        'pt-BR': 'Comunidade Aspire',
        ru: 'Сообщество Aspire',
        tr: 'Aspire Topluluğu',
        uk: 'Спільнота Aspire',
        'zh-CN': 'Aspire 社区',
      },
      items: [
        {
          label: 'Overview',
          translations: {
            da: 'Oversigt',
            de: 'Übersicht',
            en: 'Overview',
            es: 'Resumen',
            fr: 'Aperçu',
            hi: 'अवलोकन',
            id: 'Ikhtisar',
            it: 'Panoramica',
            ja: '概要',
            ko: '개요',
            'pt-BR': 'Visão geral',
            ru: 'Обзор',
            tr: 'Genel Bakış',
            uk: 'Огляд',
            'zh-CN': '概述',
          },
          slug: 'community',
        },
        {
          label: 'Contributors',
          translations: {
            da: 'Bidragydere',
            de: 'Mitwirkende',
            en: 'Contributors',
            es: 'Colaboradores',
            fr: 'Contributeurs',
            hi: 'योगदानकर्ता',
            id: 'Kontributor',
            it: 'Collaboratori',
            ja: 'コントリビューター',
            ko: '기여자',
            'pt-BR': 'Contribuidores',
            ru: 'Участники',
            tr: 'Katkıda Bulunanlar',
            uk: 'Учасники',
            'zh-CN': '贡献者',
          },
          slug: 'community/contributors',
        },
      ],
    },
    {
      label: 'Guides',
      translations: {
        da: 'Vejledninger',
        de: 'Leitfäden',
        en: 'Guides',
        es: 'Guías',
        fr: 'Guides',
        hi: 'गाइड',
        id: 'Panduan',
        it: 'Guide',
        ja: 'ガイド',
        ko: '가이드',
        'pt-BR': 'Guias',
        ru: 'Руководства',
        tr: 'Kılavuzlar',
        uk: 'Посібники',
        'zh-CN': '指南',
      },
      items: [
        {
          label: 'Contributor guide',
          translations: {
            da: 'Bidragydervejledning',
            de: 'Mitwirkenden-Leitfaden',
            en: 'Contributor guide',
            es: 'Guía del colaborador',
            fr: 'Guide du contributeur',
            hi: 'योगदानकर्ता गाइड',
            id: 'Panduan kontributor',
            it: 'Guida per i collaboratori',
            ja: 'コントリビューターガイド',
            ko: '기여자 가이드',
            'pt-BR': 'Guia do contribuinte',
            ru: 'Руководство для участников',
            tr: 'Katkıda Bulunanlar Kılavuzu',
            uk: 'Посібник для учасників',
            'zh-CN': '贡献者指南',
          },
          slug: 'community/contributor-guide',
        },
        {
          label: 'Translation guide',
          translations: {
            da: 'Oversættelsesvejledning',
            de: 'Übersetzungsleitfaden',
            en: 'Translation guide',
            es: 'Guía de traducción',
            fr: 'Guide de traduction',
            hi: 'अनुवाद गाइड',
            id: 'Panduan terjemahan',
            it: 'Guida alla traduzione',
            ja: '翻訳ガイド',
            ko: '번역 가이드',
            'pt-BR': 'Guia de tradução',
            ru: 'Руководство по переводу',
            tr: 'Çeviri kılavuzu',
            uk: 'Посібник з перекладу',
            'zh-CN': '翻译指南',
          },
          slug: 'community/translation-guide',
        },
      ],
    },
    {
      label: 'Brand assets',
      translations: {
        da: 'Brandmaterialer',
        de: 'Markenmaterialien',
        en: 'Brand assets',
        es: 'Recursos de marca',
        fr: 'Ressources de marque',
        hi: 'ब्रांड संसाधन',
        id: 'Aset merek',
        it: 'Risorse del marchio',
        ja: 'ブランドアセット',
        ko: '브랜드 자산',
        'pt-BR': 'Recursos da marca',
        ru: 'Материалы бренда',
        tr: 'Marka kaynakları',
        uk: 'Матеріали бренду',
        'zh-CN': '品牌资源',
      },
      items: [
        {
          label: 'Overview',
          translations: {
            da: 'Oversigt',
            de: 'Übersicht',
            en: 'Overview',
            es: 'Resumen',
            fr: 'Aperçu',
            hi: 'अवलोकन',
            id: 'Ikhtisar',
            it: 'Panoramica',
            ja: '概要',
            ko: '개요',
            'pt-BR': 'Visão geral',
            ru: 'Обзор',
            tr: 'Genel Bakış',
            uk: 'Огляд',
            'zh-CN': '概述',
          },
          slug: 'community/brand',
        },
        {
          label: 'Logos and icons',
          translations: {
            da: 'Logoer og ikoner',
            de: 'Logos und Symbole',
            en: 'Logos and icons',
            es: 'Logotipos e iconos',
            fr: 'Logos et icônes',
            hi: 'लोगो और आइकन',
            id: 'Logo dan ikon',
            it: 'Loghi e icone',
            ja: 'ロゴとアイコン',
            ko: '로고 및 아이콘',
            'pt-BR': 'Logotipos e ícones',
            ru: 'Логотипы и значки',
            tr: 'Logolar ve simgeler',
            uk: 'Логотипи та значки',
            'zh-CN': '徽标和图标',
          },
          slug: 'community/brand/logos',
        },
        {
          label: 'Colors',
          translations: {
            da: 'Farver',
            de: 'Farben',
            en: 'Colors',
            es: 'Colores',
            fr: 'Couleurs',
            hi: 'रंग',
            id: 'Warna',
            it: 'Colori',
            ja: '色',
            ko: '색상',
            'pt-BR': 'Cores',
            ru: 'Цвета',
            tr: 'Renkler',
            uk: 'Кольори',
            'zh-CN': '颜色',
          },
          slug: 'community/brand/colors',
        },
        {
          label: 'Typography',
          translations: {
            da: 'Typografi',
            de: 'Typografie',
            en: 'Typography',
            es: 'Tipografía',
            fr: 'Typographie',
            hi: 'टाइपोग्राफी',
            id: 'Tipografi',
            it: 'Tipografia',
            ja: 'タイポグラフィ',
            ko: '타이포그래피',
            'pt-BR': 'Tipografia',
            ru: 'Типографика',
            tr: 'Tipografi',
            uk: 'Типографіка',
            'zh-CN': '排版',
          },
          slug: 'community/brand/typography',
        },
        {
          label: 'Usage guidance',
          translations: {
            da: 'Brugsvejledning',
            de: 'Nutzungshinweise',
            en: 'Usage guidance',
            es: 'Guía de uso',
            fr: "Conseils d'utilisation",
            hi: 'उपयोग मार्गदर्शन',
            id: 'Panduan penggunaan',
            it: "Linee guida per l'uso",
            ja: '使用ガイド',
            ko: '사용 지침',
            'pt-BR': 'Orientações de uso',
            ru: 'Рекомендации по использованию',
            tr: 'Kullanım rehberi',
            uk: 'Рекомендації щодо використання',
            'zh-CN': '使用指南',
          },
          slug: 'community/brand/usage',
        },
      ],
    },
    {
      label: 'Live Streams',
      translations: {
        da: 'Livestreams',
        de: 'Livestreams',
        en: 'Live Streams',
        es: 'Transmisiones en directo',
        fr: 'Diffusions en direct',
        hi: 'लाइव स्ट्रीम',
        id: 'Siaran langsung',
        it: 'Dirette streaming',
        ja: 'ライブ配信',
        ko: '라이브 스트림',
        'pt-BR': 'Transmissões ao vivo',
        ru: 'Прямые эфиры',
        tr: 'Canlı Yayınlar',
        uk: 'Прямі трансляції',
        'zh-CN': '直播',
      },
      slug: 'community/videos',
    },
    {
      label: 'Aspire Conf',
      slug: 'aspireconf',
      badge: {
        text: 'Mar 23',
        variant: 'tip',
      },
    },
    {
      label: 'Thanks',
      translations: {
        da: 'Tak',
        de: 'Danke',
        en: 'Thanks',
        es: 'Agradecimientos',
        fr: 'Remerciements',
        hi: 'धन्यवाद',
        id: 'Terima Kasih',
        it: 'Ringraziamenti',
        ja: '謝辞',
        ko: '감사의 말',
        'pt-BR': 'Agradecimentos',
        ru: 'Благодарности',
        tr: 'Teşekkürler',
        uk: 'Подяки',
        'zh-CN': '致谢',
      },
      slug: 'community/thanks',
    },
  ],
};
