import type { StarlightSidebarTopicsUserConfig } from 'starlight-sidebar-topics';

export const dashboardTopics: StarlightSidebarTopicsUserConfig = {
  label: {
    en: 'Dashboard',
    es: 'Panel',
    fr: 'Tableau de bord',
    de: 'Dashboard',
    it: 'Dashboard',
    ru: 'Панель управления',
    'zh-CN': '仪表板',
    da: 'Dashboard',
    hi: 'डैशबोर्ड',
    id: 'Dasbor',
    ja: 'ダッシュボード',
    ko: '대시보드',
    'pt-BR': 'Painel',
    tr: 'Gösterge Paneli',
    uk: 'Панель керування',
  },
  link: '/dashboard/',
  icon: 'seti:happenings',
  items: [
    {
      label: 'Aspire dashboard',
      translations: {
        da: 'Aspire-dashboard',
        de: 'Aspire-Dashboard',
        en: 'Aspire dashboard',
        es: 'Panel de Aspire',
        fr: 'Tableau de bord Aspire',
        hi: 'Aspire डैशबोर्ड',
        id: 'Dasbor Aspire',
        it: 'Dashboard di Aspire',
        ja: 'Aspireダッシュボード',
        ko: 'Aspire 대시보드',
        'pt-BR': 'Painel Aspire',
        ru: 'Панель управления Aspire',
        tr: 'Aspire Gösterge Paneli',
        uk: 'Панель керування Aspire',
        'zh-CN': 'Aspire 仪表板',
      },
      items: [
        {
          label: 'Overview',
          translations: {
            da: 'Oversigt',
            de: 'Übersicht',
            en: 'Overview',
            es: 'Resumen',
            fr: 'Aperçu',
            hi: 'अवलोकन',
            id: 'Ikhtisar',
            it: 'Panoramica',
            ja: '概要',
            ko: '개요',
            'pt-BR': 'Visão geral',
            ru: 'Обзор',
            tr: 'Genel bakış',
            uk: 'Огляд',
            'zh-CN': '概述',
          },
          slug: 'dashboard',
        },
        {
          label: 'What is the Aspire dashboard?',
          translations: {
            da: 'Hvad er Aspire-dashboardet?',
            de: 'Was ist das Aspire-Dashboard?',
            en: 'What is the Aspire dashboard?',
            es: '¿Qué es el panel de Aspire?',
            fr: "Qu'est-ce que le tableau de bord Aspire ?",
            hi: 'Aspire डैशबोर्ड क्या है?',
            id: 'Apa itu dasbor Aspire?',
            it: "Cos'è il dashboard di Aspire?",
            ja: 'Aspireダッシュボードとは何ですか？',
            ko: 'Aspire 대시보드란 무엇입니까?',
            'pt-BR': 'O que é o painel Aspire?',
            ru: 'Что такое панель Aspire?',
            tr: 'Aspire gösterge paneli nedir?',
            uk: 'Що таке панель Aspire?',
            'zh-CN': 'Aspire 仪表板是什么？',
          },
          slug: 'dashboard/overview',
        },
        {
          label: 'Explore features',
          translations: {
            da: 'Udforsk funktioner',
            de: 'Funktionen erkunden',
            en: 'Explore features',
            es: 'Explorar funciones',
            fr: 'Explorer les fonctionnalités',
            hi: 'विशेषताएँ एक्सप्लोर करें',
            id: 'Jelajahi fitur',
            it: 'Esplora funzionalità',
            ja: '機能を探る',
            ko: '기능 탐색',
            'pt-BR': 'Explorar recursos',
            ru: 'Изучение функций',
            tr: 'Özellikleri keşfet',
            uk: 'Дослідити функції',
            'zh-CN': '探索功能',
          },
          slug: 'dashboard/explore',
        },
      ],
    },
    {
      label: 'AI features',
      translations: {
        da: 'AI-funktioner',
        de: 'KI-Funktionen',
        en: 'AI features',
        es: 'Funciones de IA',
        fr: "Fonctionnalités d'IA",
        hi: 'एआई सुविधाएँ',
        id: 'Fitur AI',
        it: "Funzionalità dell'IA",
        ja: 'AI機能',
        ko: 'AI 기능',
        'pt-BR': 'Recursos de IA',
        ru: 'Функции ИИ',
        tr: 'Yapay zeka özellikleri',
        uk: 'Функції ШІ',
        'zh-CN': '人工智能功能',
      },
      items: [
        {
          label: 'GitHub Copilot',
          slug: 'dashboard/copilot',
        },
        {
          label: 'Aspire MCP server',
          translations: {
            da: 'Aspire MCP-server',
            de: 'Aspire MCP-Server',
            en: 'Aspire MCP server',
            es: 'Servidor Aspire MCP',
            fr: 'Serveur Aspire MCP',
            hi: 'Aspire MCP सर्वर',
            id: 'Server Aspire MCP',
            it: 'Server Aspire MCP',
            ja: 'Aspire MCPサーバー',
            ko: 'Aspire MCP 서버',
            'pt-BR': 'Servidor Aspire MCP',
            ru: 'Сервер Aspire MCP',
            tr: 'Aspire MCP sunucusu',
            uk: 'Сервер Aspire MCP',
            'zh-CN': 'Aspire MCP 服务器',
          },
          slug: 'dashboard/mcp-server',
        },
      ],
    },
    {
      label: 'Standalone mode',
      translations: {
        da: 'Selvstændig tilstand',
        de: 'Eigenständiger Modus',
        en: 'Standalone mode',
        es: 'Modo independiente',
        fr: 'Mode autonome',
        hi: 'स्टैंडअलोन मोड',
        id: 'Mode mandiri',
        it: 'Modalità autonoma',
        ja: 'スタンドアロンモード',
        ko: '독립 실행 모드',
        'pt-BR': 'Modo autônomo',
        ru: 'Автономный режим',
        tr: 'Bağımsız mod',
        uk: 'Автономний режим',
        'zh-CN': '独立模式',
      },
      items: [
        { label: 'Overview', slug: 'dashboard/standalone' },
        {
          label: 'Python apps',
          slug: 'dashboard/standalone-for-python',
        },
        {
          label: 'Node.js apps',
          slug: 'dashboard/standalone-for-nodejs',
        },
      ],
    },
    {
      label: 'Configuration',
      translations: {
        da: 'Konfiguration',
        de: 'Konfiguration',
        en: 'Configuration',
        es: 'Configuración',
        fr: 'Configuration',
        hi: 'कॉन्फ़िगरेशन',
        id: 'Konfigurasi',
        it: 'Configurazione',
        ja: '構成',
        ko: '구성',
        'pt-BR': 'Configuração',
        ru: 'Конфигурация',
        tr: 'Yapılandırma',
        uk: 'Конфігурація',
        'zh-CN': '配置',
      },
      slug: 'dashboard/configuration',
    },
    {
      label: 'Security considerations',
      translations: {
        da: 'Sikkerhedsovervejelser',
        de: 'Sicherheitsüberlegungen',
        en: 'Security considerations',
        es: 'Consideraciones de seguridad',
        fr: 'Considérations de sécurité',
        hi: 'सुरक्षा संबंधी विचार',
        id: 'Pertimbangan keamanan',
        it: 'Considerazioni sulla sicurezza',
        ja: 'セキュリティに関する考慮事項',
        ko: '보안 고려 사항',
        'pt-BR': 'Considerações de segurança',
        ru: 'Соображения безопасности',
        tr: 'Güvenlik değerlendirmeleri',
        uk: 'Міркування щодо безпеки',
        'zh-CN': '安全注意事项',
      },
      slug: 'dashboard/security-considerations',
    },
    {
      label: 'Telemetry',
      translations: {
        da: 'Telemetri',
        de: 'Telemetrie',
        en: 'Telemetry',
        es: 'Telemetría',
        fr: 'Télémétrie',
        hi: 'टेलीमेट्री',
        id: 'Telemetri',
        it: 'Telemetria',
        ja: 'テレメトリー',
        ko: '원격 측정',
        'pt-BR': 'Telemetria',
        ru: 'Телеметрия',
        tr: 'Telemetri',
        uk: 'Телеметрія',
        'zh-CN': '遥测',
      },
      items: [
        {
          label: 'Enable browser telemetry',
          translations: {
            da: 'Aktivér browsertelemetri',
            de: 'Browser-Telemetrie aktivieren',
            en: 'Enable browser telemetry',
            es: 'Habilitar telemetría del navegador',
            fr: 'Activer la télémétrie du navigateur',
            hi: 'ब्राउज़र टेलीमेट्री सक्षम करें',
            id: 'Aktifkan telemetri browser',
            it: 'Abilita telemetria del browser',
            ja: 'ブラウザのテレメトリを有効にする',
            ko: '브라우저 원격 분석 활성화',
            'pt-BR': 'Ativar telemetria do navegador',
            ru: 'Включить телеметрию браузера',
            tr: 'Tarayıcı telemetrisi etkinleştirme',
            uk: 'Увімкнути телеметрію браузера',
            'zh-CN': '启用浏览器遥测',
          },
          slug: 'dashboard/enable-browser-telemetry',
        },
        {
          label: 'Microsoft telemetry',
          translations: {
            da: 'Microsoft telemetri',
            de: 'Microsoft-Telemetrie',
            en: 'Microsoft telemetry',
            es: 'Telemetría de Microsoft',
            fr: 'Télémétrie Microsoft',
            hi: 'Microsoft टेलीमेट्री',
            id: 'Telemetri Microsoft',
            it: 'Telemetria Microsoft',
            ja: 'Microsoft テレメトリ',
            ko: 'Microsoft 원격 분석',
            'pt-BR': 'Telemetria da Microsoft',
            ru: 'Телеметрия Microsoft',
            tr: 'Microsoft telemetrisi',
            uk: 'Телеметрія Microsoft',
            'zh-CN': 'Microsoft 遥测',
          },
          slug: 'dashboard/microsoft-collected-dashboard-telemetry',
        },
      ],
    },
  ],
};
