import type { StarlightSidebarTopicsUserConfig } from 'starlight-sidebar-topics';

export const dashboardTopics: StarlightSidebarTopicsUserConfig = {
  label: {
    en: 'Dashboard',
    es: 'Panel',
    fr: 'Tableau de bord',
    de: 'Dashboard',
    it: 'Dashboard',
    pt: 'Painel',
    ru: 'Панель управления',
    'zh-CN': '仪表板',
    da: 'Dashboard',
    hi: 'डैशबोर्ड',
    id: 'Dasbor',
    ja: 'ダッシュボード',
    ko: '대시보드',
    'pt-BR': 'Painel',
    'pt-PT': 'Painel',
    tr: 'Gösterge Paneli',
    uk: 'Панель керування',
  },
  link: '/dashboard/overview',
  icon: 'seti:happenings',
  items: [
    {
      label: 'Overview',
      translations: {
        da: 'Oversigt',
        de: 'Übersicht',
        en: 'Overview',
        es: 'Descripción general',
        fr: "Vue d'ensemble",
        hi: 'अवलोकन',
        id: 'Ikhtisar',
        it: 'Panoramica',
        ja: '概要',
        ko: '개요',
        pt: 'Visão geral',
        'pt-BR': 'Visão geral',
        'pt-PT': 'Visão geral',
        ru: 'Обзор',
        tr: 'Genel Bakış',
        uk: 'Огляд',
        'zh-CN': '概述',
      },
      slug: 'dashboard/overview',
    },
    {
      label: 'Explore features',
      translations: {
        da: 'Udforsk funktioner',
        de: 'Funktionen erkunden',
        en: 'Explore features',
        es: 'Explorar funciones',
        fr: 'Explorer les fonctionnalités',
        hi: 'विशेषताएँ एक्सप्लोर करें',
        id: 'Jelajahi fitur',
        it: 'Esplora funzionalità',
        ja: '機能を探る',
        ko: '기능 탐색',
        pt: 'Explorar recursos',
        'pt-BR': 'Explorar recursos',
        'pt-PT': 'Explorar recursos',
        ru: 'Изучение функций',
        tr: 'Özellikleri keşfet',
        uk: 'Дослідити функції',
        'zh-CN': '探索功能',
      },
      slug: 'dashboard/explore',
    },
    {
      label: 'GitHub Copilot',
      slug: 'dashboard/copilot',
    },
    {
      label: 'Aspire MCP server',
      translations: {
        da: 'Aspire MCP-server',
        de: 'Aspire MCP-Server',
        en: 'Aspire MCP server',
        es: 'Servidor Aspire MCP',
        fr: 'Serveur Aspire MCP',
        hi: 'Aspire MCP सर्वर',
        id: 'Server Aspire MCP',
        it: 'Server Aspire MCP',
        ja: 'Aspire MCPサーバー',
        ko: 'Aspire MCP 서버',
        pt: 'Servidor Aspire MCP',
        'pt-BR': 'Servidor Aspire MCP',
        'pt-PT': 'Servidor Aspire MCP',
        ru: 'Сервер Aspire MCP',
        tr: 'Aspire MCP sunucusu',
        uk: 'Сервер Aspire MCP',
        'zh-CN': 'Aspire MCP 服务器',
      },
      slug: 'dashboard/mcp-server',
    },
    {
      label: 'Standalone mode',
      translations: {
        da: 'Selvstændig tilstand',
        de: 'Eigenständiger Modus',
        en: 'Standalone mode',
        es: 'Modo independiente',
        fr: 'Mode autonome',
        hi: 'स्टैंडअलोन मोड',
        id: 'Mode mandiri',
        it: 'Modalità autonoma',
        ja: 'スタンドアロンモード',
        ko: '독립 실행 모드',
        pt: 'Modo autônomo',
        'pt-BR': 'Modo autônomo',
        'pt-PT': 'Modo autónomo',
        ru: 'Автономный режим',
        tr: 'Bağımsız mod',
        uk: 'Автономний режим',
        'zh-CN': '独立模式',
      },
      items: [
        { label: 'Overview', slug: 'dashboard/standalone' },
        {
          label: 'Python apps',
          slug: 'dashboard/standalone-for-python',
        },
        {
          label: 'Node.js apps',
          slug: 'dashboard/standalone-for-nodejs',
        },
      ],
    },
    {
      label: 'Configuration',
      translations: {
        da: 'Konfiguration',
        de: 'Konfiguration',
        en: 'Configuration',
        es: 'Configuración',
        fr: 'Configuration',
        hi: 'कॉन्फ़िगरेशन',
        id: 'Konfigurasi',
        it: 'Configurazione',
        ja: '構成',
        ko: '구성',
        pt: 'Configuração',
        'pt-BR': 'Configuração',
        'pt-PT': 'Configuração',
        ru: 'Конфигурация',
        tr: 'Yapılandırma',
        uk: 'Конфігурація',
        'zh-CN': '配置',
      },
      slug: 'dashboard/configuration',
    },
    {
      label: 'Security considerations',
      translations: {
        da: 'Sikkerhedsovervejelser',
        de: 'Sicherheitsüberlegungen',
        en: 'Security considerations',
        es: 'Consideraciones de seguridad',
        fr: 'Considérations de sécurité',
        hi: 'सुरक्षा संबंधी विचार',
        id: 'Pertimbangan keamanan',
        it: 'Considerazioni sulla sicurezza',
        ja: 'セキュリティに関する考慮事項',
        ko: '보안 고려 사항',
        pt: 'Considerações de segurança',
        'pt-BR': 'Considerações de segurança',
        'pt-PT': 'Considerações de segurança',
        ru: 'Соображения безопасности',
        tr: 'Güvenlik değerlendirmeleri',
        uk: 'Міркування щодо безпеки',
        'zh-CN': '安全注意事项',
      },
      slug: 'dashboard/security-considerations',
    },
    {
      label: 'Enable browser telemetry',
      translations: {
        da: 'Aktivér browsertelemetri',
        de: 'Browser-Telemetrie aktivieren',
        en: 'Enable browser telemetry',
        es: 'Habilitar telemetría del navegador',
        fr: 'Activer la télémétrie du navigateur',
        hi: 'ब्राउज़र टेलीमेट्री सक्षम करें',
        id: 'Aktifkan telemetri browser',
        it: 'Abilita telemetria del browser',
        ja: 'ブラウザのテレメトリを有効にする',
        ko: '브라우저 원격 분석 활성화',
        pt: 'Ativar telemetria do navegador',
        'pt-BR': 'Ativar telemetria do navegador',
        'pt-PT': 'Ativar telemetria do navegador',
        ru: 'Включить телеметрию браузера',
        tr: 'Tarayıcı telemetrisi etkinleştirme',
        uk: 'Увімкнути телеметрію браузера',
        'zh-CN': '启用浏览器遥测',
      },
      slug: 'dashboard/enable-browser-telemetry',
    },
    {
      label: 'Microsoft telemetry',
      translations: {
        da: 'Microsoft telemetri',
        de: 'Microsoft-Telemetrie',
        en: 'Microsoft telemetry',
        es: 'Telemetría de Microsoft',
        fr: 'Télémétrie Microsoft',
        hi: 'Microsoft टेलीमेट्री',
        id: 'Telemetri Microsoft',
        it: 'Telemetria Microsoft',
        ja: 'Microsoft テレメトリ',
        ko: 'Microsoft 원격 분석',
        pt: 'Telemetria da Microsoft',
        'pt-BR': 'Telemetria da Microsoft',
        'pt-PT': 'Telemetria da Microsoft',
        ru: 'Телеметрия Microsoft',
        tr: 'Microsoft telemetrisi',
        uk: 'Телеметрія Microsoft',
        'zh-CN': 'Microsoft 遥测',
      },
      slug: 'dashboard/microsoft-collected-dashboard-telemetry',
    },
  ],
};
