import type { StarlightSidebarTopicsUserConfig } from 'starlight-sidebar-topics';

export const deploymentTopics: StarlightSidebarTopicsUserConfig = {
  label: {
    da: 'Udrulning',
    de: 'Bereitstellung',
    en: 'Deployment',
    es: 'Despliegue',
    fr: 'Déploiement',
    hi: 'तैनाती',
    id: 'Penyebaran',
    it: 'Distribuzione',
    ja: 'デプロイ',
    ko: '배포',
    'pt-BR': 'Implantação',
    'pt-PT': 'Implementação',
    ru: 'Развертывание',
    tr: 'Dağıtım',
    uk: 'Розгортання',
    'zh-CN': '部署',
  },
  link: 'deployment/overview',
  icon: 'rocket',
  items: [
    {
      label: 'Overview',
      translations: {
        da: 'Oversigt',
        de: 'Übersicht',
        en: 'Overview',
        es: 'Descripción general',
        fr: "Vue d'ensemble",
        hi: 'अवलोकन',
        id: 'Ikhtisar',
        it: 'Panoramica',
        ja: '概要',
        ko: '개요',
        'pt-BR': 'Visão geral',
        'pt-PT': 'Visão geral',
        ru: 'Обзор',
        tr: 'Genel Bakış',
        uk: 'Огляд',
        'zh-CN': '概述',
      },
      slug: 'deployment/overview',
    },
    {
      label: 'Deployment manifest format',
      translations: {
        da: 'Udrulningsmanifestformat',
        de: 'Bereitstellungsmanifestformat',
        en: 'Deployment manifest format',
        es: 'Formato de manifiesto de despliegue',
        fr: 'Format de manifeste de déploiement',
        hi: 'तैनाती मैनिफ़ेस्ट प्रारूप',
        id: 'Format manifes penyebaran',
        it: 'Formato del manifesto di distribuzione',
        ja: 'デプロイマニフェスト形式',
        ko: '배포 매니페스트 형식',
        'pt-BR': 'Formato de manifesto de implantação',
        'pt-PT': 'Formato de manifesto de implementação',
        ru: 'Формат манифеста развертывания',
        tr: 'Dağıtım bildirimi biçimi',
        uk: 'Формат маніфесту розгортання',
        'zh-CN': '部署清单格式',
      },
      slug: 'deployment/manifest-format',
    },
    {
      label: 'Deployment state caching',
      translations: {
        da: 'Cachelagring af udrulningstilstand',
        de: 'Zwischenspeichern des Bereitstellungsstatus',
        en: 'Deployment state caching',
        es: 'Almacenamiento en caché del estado de despliegue',
        fr: "Mise en cache de l'état de déploiement",
        hi: 'तैनाती स्थिति कैशिंग',
        id: 'Caching status penyebaran',
        it: 'Memorizzazione nella cache dello stato di distribuzione',
        ja: 'デプロイ状態のキャッシュ',
        ko: '배포 상태 캐싱',
        'pt-BR': 'Cache de estado de implantação',
        'pt-PT': 'Cache de estado de implementação',
        ru: 'Кэширование состояния развертывания',
        tr: 'Dağıtım durumu önbelleğe alma',
        uk: 'Кешування стану розгортання',
        'zh-CN': '部署状态缓存',
      },
      slug: 'deployment/deployment-state-caching',
    },
    {
      label: 'Custom deployment pipelines',
      translations: {
        da: 'Brugerdefinerede implementeringspipelines',
        de: 'Benutzerdefinierte Bereitstellungspipelines',
        en: 'Custom deployment pipelines',
        es: 'Canalizaciones de despliegue personalizadas',
        fr: 'Pipelines de déploiement personnalisés',
        hi: 'कस्टम तैनाती पाइपलाइन',
        id: 'Pipeline penyebaran kustom',
        it: 'Pipeline di distribuzione personalizzate',
        ja: 'カスタム デプロイ パイプライン',
        ko: '사용자 지정 배포 파이프라인',
        'pt-BR': 'Pipelines de implantação personalizados',
        'pt-PT': 'Pipelines de implementação personalizados',
        ru: 'Пользовательские конвейеры развертывания',
        tr: 'Özel dağıtım işlem hatları',
        uk: 'Користувацькі конвеєри розгортання',
        'zh-CN': '自定义部署管道',
      },
      slug: 'deployment/custom-deployments',
    },
    {
      label: 'Deploy to Azure',
      collapsed: false,
      translations: {
        da: 'Udrul til Azure',
        de: 'In Azure bereitstellen',
        en: 'Deploy to Azure',
        es: 'Desplegar en Azure',
        fr: 'Déployer sur Azure',
        hi: 'Azure पर तैनात करें',
        id: 'Deploy ke Azure',
        it: 'Distribuisci in Azure',
        ja: 'Azure にデプロイ',
        ko: 'Azure에 배포',
        'pt-BR': 'Implantar no Azure',
        'pt-PT': 'Implementar no Azure',
        ru: 'Развертывание в Azure',
        tr: "Azure'a dağıt",
        uk: 'Розгортання в Azure',
        'zh-CN': '部署到 Azure',
      },
      items: [
        {
          label: 'Deploy using the Aspire CLI',
          translations: {
            da: 'Udrul ved hjælp af Aspire CLI',
            de: 'Bereitstellen mit der Aspire CLI',
            en: 'Deploy using the Aspire CLI',
            es: 'Desplegar usando la CLI de Aspire',
            fr: "Déployer à l'aide de la CLI Aspire",
            hi: 'Aspire CLI का उपयोग करके तैनात करें',
            id: 'Deploy menggunakan Aspire CLI',
            it: 'Distribuisci usando Aspire CLI',
            ja: 'Aspire CLI を使用したデプロイ',
            ko: 'Aspire CLI를 사용하여 배포',
            'pt-BR': 'Implantar usando a CLI do Aspire',
            'pt-PT': 'Implementar usando a CLI do Aspire',
            ru: 'Развертывание с помощью Aspire CLI',
            tr: 'Aspire CLI kullanarak dağıt',
            uk: 'Розгортання за допомогою Aspire CLI',
            'zh-CN': '使用 Aspire CLI 部署',
          },
          slug: 'deployment/azure/aca-deployment-aspire-cli',
        },
        {
          label: 'Azure security best practices',
          translations: {
            da: 'Bedste praksis for Azure-sikkerhed',
            de: 'Bewährte Methoden für Azure-Sicherheit',
            en: 'Azure security best practices',
            es: 'Prácticas recomendadas de seguridad de Azure',
            fr: 'Bonnes pratiques de sécurité Azure',
            hi: 'Azure सुरक्षा सर्वोत्तम प्रथाएँ',
            id: 'Praktik terbaik keamanan Azure',
            it: 'Procedure consigliate per la sicurezza di Azure',
            ja: 'Azure セキュリティのベスト プラクティス',
            ko: 'Azure 보안 모범 사례',
            'pt-BR': 'Práticas recomendadas de segurança do Azure',
            'pt-PT': 'Melhores práticas de segurança do Azure',
            ru: 'Рекомендации по безопасности Azure',
            tr: 'Azure güvenlik en iyi uygulamaları',
            uk: 'Найкращі практики безпеки Azure',
            'zh-CN': 'Azure 安全最佳实践',
          },
          slug: 'deployment/azure/azure-security-best-practices',
        },
      ],
    },
  ],
};
