import type { StarlightSidebarTopicsUserConfig } from 'starlight-sidebar-topics';

export const deploymentTopics: StarlightSidebarTopicsUserConfig = {
  label: {
    da: 'Udrulning',
    de: 'Bereitstellung',
    en: 'Deployment',
    es: 'Despliegue',
    fr: 'Déploiement',
    hi: 'तैनाती',
    id: 'Penyebaran',
    it: 'Distribuzione',
    ja: 'デプロイ',
    ko: '배포',
    'pt-BR': 'Implantação',
    ru: 'Развертывание',
    tr: 'Dağıtım',
    uk: 'Розгортання',
    'zh-CN': '部署',
  },
  link: '/deployment/',
  icon: 'rocket',
  items: [
    {
      label: 'Deployment',
      translations: {
        da: 'Udrulning',
        de: 'Bereitstellung',
        en: 'Deployment',
        es: 'Despliegue',
        fr: 'Déploiement',
        hi: 'तैनाती',
        id: 'Penyebaran',
        it: 'Distribuzione',
        ja: 'デプロイ',
        ko: '배포',
        'pt-BR': 'Implantação',
        ru: 'Развертывание',
        tr: 'Dağıtım',
        uk: 'Розгортання',
        'zh-CN': '部署',
      },
      slug: 'deployment',
    },
    {
      label: 'Overview',
      translations: {
        da: 'Oversigt',
        de: 'Übersicht',
        en: 'Overview',
        es: 'Descripción general',
        fr: "Vue d'ensemble",
        hi: 'अवलोकन',
        id: 'Ikhtisar',
        it: 'Panoramica',
        ja: '概要',
        ko: '개요',
        'pt-BR': 'Visão geral',
        ru: 'Обзор',
        tr: 'Genel Bakış',
        uk: 'Огляд',
        'zh-CN': '概述',
      },
      slug: 'deployment/overview',
    },
    {
      label: 'Environments',
      slug: 'deployment/environments',
    },
    {
      label: 'Pipelines (aspire do)',
      slug: 'deployment/pipelines',
    },
    {
      label: 'Deploy to Docker Compose',
      slug: 'deployment/docker-compose',
    },
    {
      label: 'Deploy to Kubernetes',
      slug: 'deployment/kubernetes',
    },
    {
      label: 'Deploy to Azure',
      collapsed: false,
      translations: {
        da: 'Udrul til Azure',
        de: 'In Azure bereitstellen',
        en: 'Deploy to Azure',
        es: 'Desplegar en Azure',
        fr: 'Déployer sur Azure',
        hi: 'Azure पर तैनात करें',
        id: 'Deploy ke Azure',
        it: 'Distribuisci in Azure',
        ja: 'Azure にデプロイ',
        ko: 'Azure에 배포',
        'pt-BR': 'Implantar no Azure',
        ru: 'Развертывание в Azure',
        tr: "Azure'a dağıt",
        uk: 'Розгортання в Azure',
        'zh-CN': '部署到 Azure',
      },
      items: [
        {
          label: 'Deploy using the Aspire CLI',
          translations: {
            da: 'Udrul ved hjælp af Aspire CLI',
            de: 'Bereitstellen mit der Aspire CLI',
            en: 'Deploy using the Aspire CLI',
            es: 'Desplegar usando la CLI de Aspire',
            fr: "Déployer à l'aide de la CLI Aspire",
            hi: 'Aspire CLI का उपयोग करके तैनात करें',
            id: 'Deploy menggunakan Aspire CLI',
            it: 'Distribuisci usando Aspire CLI',
            ja: 'Aspire CLI を使用したデプロイ',
            ko: 'Aspire CLI를 사용하여 배포',
            'pt-BR': 'Implantar usando a CLI do Aspire',
            ru: 'Развертывание с помощью Aspire CLI',
            tr: 'Aspire CLI kullanarak dağıt',
            uk: 'Розгортання за допомогою Aspire CLI',
            'zh-CN': '使用 Aspire CLI 部署',
          },
          slug: 'deployment/azure/aca-deployment-aspire-cli',
        },
        {
          label: 'Customize Azure Container Apps',
          slug: 'deployment/azure/customize-container-apps',
        },
        {
          label: 'Azure security best practices',
          translations: {
            da: 'Bedste praksis for Azure-sikkerhed',
            de: 'Bewährte Methoden für Azure-Sicherheit',
            en: 'Azure security best practices',
            es: 'Prácticas recomendadas de seguridad de Azure',
            fr: 'Bonnes pratiques de sécurité Azure',
            hi: 'Azure सुरक्षा सर्वोत्तम प्रथाएँ',
            id: 'Praktik terbaik keamanan Azure',
            it: 'Procedure consigliate per la sicurezza di Azure',
            ja: 'Azure セキュリティのベスト プラクティス',
            ko: 'Azure 보안 모범 사례',
            'pt-BR': 'Práticas recomendadas de segurança do Azure',
            ru: 'Рекомендации по безопасности Azure',
            tr: 'Azure güvenlik en iyi uygulamaları',
            uk: 'Найкращі практики безпеки Azure',
            'zh-CN': 'Azure 安全最佳实践',
          },
          slug: 'deployment/azure/azure-security-best-practices',
        },
        {
          label: 'Azure Developer CLI (azd)',
          collapsed: true,
          items: [
            {
              label: 'Overview',
              slug: 'deployment/azure/azure-developer-cli',
            },
            {
              label: 'Deployment manifest format',
              slug: 'deployment/azure/manifest-format',
            },
          ],
        },
      ],
    },
    {
      label: 'Deploy JavaScript apps',
      slug: 'deployment/javascript-apps',
    },
    {
      label: 'App lifecycle (CI/CD)',
      slug: 'deployment/app-lifecycle',
    },
    {
      label: 'Advanced',
      collapsed: true,
      items: [
        {
          label: 'Deployment state caching',
          slug: 'deployment/deployment-state-caching',
        },
        {
          label: 'Custom deployment pipelines',
          slug: 'deployment/custom-deployments',
        },
      ],
    },
  ],
};
