import type { StarlightSidebarTopicsUserConfig } from 'starlight-sidebar-topics';

export const referenceTopics: StarlightSidebarTopicsUserConfig[number] = {
  label: {
    en: 'Reference',
    es: 'Referencia',
    fr: 'Référence',
    de: 'Referenz',
    it: 'Riferimento',
    pt: 'Referência',
    ru: 'Справочник',
    'zh-CN': '参考',
    da: 'Reference',
    hi: 'संदर्भ',
    id: 'Referensi',
    ja: 'リファレンス',
    ko: '참고 자료',
    'pt-BR': 'Referência',
    tr: 'Referans',
    uk: 'Довідник',
  },
  link: '/reference/overview',
  icon: 'seti:json',
  items: [
    {
      label: 'Overview',
      translations: {
        da: 'Oversigt',
        de: 'Übersicht',
        en: 'Overview',
        es: 'Descripción general',
        fr: "Vue d'ensemble",
        hi: 'अवलोकन',
        id: 'Ikhtisar',
        it: 'Panoramica',
        ja: '概要',
        ko: '개요',
        pt: 'Visão geral',
        'pt-BR': 'Visão geral',
        ru: 'Обзор',
        tr: 'Genel Bakış',
        uk: 'Огляд',
        'zh-CN': '概述',
      },
      slug: 'reference/overview',
    },
    {
      label: 'Samples',
      translations: {
        da: 'Eksempler',
        de: 'Beispiele',
        en: 'Samples',
        es: 'Muestras',
        fr: 'Exemples',
        hi: 'नमूने',
        id: 'Sampel',
        it: 'Esempi',
        ja: 'サンプル',
        ko: '샘플',
        pt: 'Exemplos',
        'pt-BR': 'Exemplos',
        ru: 'Примеры',
        tr: 'Örnekler',
        uk: 'Зразки',
        'zh-CN': '示例',
      },
      slug: 'reference/samples',
    },
    {
      label: 'API reference',
      translations: {
        da: 'API reference',
        de: 'API-Referenz',
        en: 'API reference',
        es: 'Referencia de API',
        fr: "Référence de l'API",
        hi: 'एपीआई संदर्भ',
        id: 'Referensi API',
        it: "Riferimento all'API",
        ja: 'APIリファレンス',
        ko: 'API 참조',
        pt: 'Referência da API',
        'pt-BR': 'Referência da API',
        ru: 'Справочник по API',
        tr: 'API referansı',
        uk: 'Довідник API',
        'zh-CN': 'API参考',
      },
      collapsed: false,
      items: [
        {
          label: 'Search C# APIs',
          translations: {
            da: "Søg i C# API'er",
            de: 'C# APIs durchsuchen',
            en: 'Search C# APIs',
            es: 'Buscar API de C#',
            fr: 'Rechercher les API C#',
            hi: 'C# एपीआई खोजें',
            id: 'Cari API C#',
            it: 'Cerca API C#',
            ja: 'C# APIを検索する',
            ko: 'C# API 검색',
            pt: 'Pesquisar APIs C#',
            'pt-BR': 'Pesquisar APIs C#',
            ru: 'Поиск C# API',
            tr: "C# API'leri Arayın",
            uk: 'Пошук C# API',
            'zh-CN': '搜索 C# API',
          },
          link: '/reference/api/csharp/',
        },
        {
          label: 'Search TypeScript APIs',
          translations: {
            da: "Søg i TypeScript API'er",
            de: 'TypeScript APIs durchsuchen',
            en: 'Search TypeScript APIs',
            es: 'Buscar API de TypeScript',
            fr: 'Rechercher les API TypeScript',
            hi: 'TypeScript एपीआई खोजें',
            id: 'Cari API TypeScript',
            it: 'Cerca API TypeScript',
            ja: 'TypeScript APIを検索する',
            ko: 'TypeScript API 검색',
            pt: 'Pesquisar APIs TypeScript',
            'pt-BR': 'Pesquisar APIs TypeScript',
            ru: 'Поиск TypeScript API',
            tr: "TypeScript API'leri Arayın",
            uk: 'Пошук TypeScript API',
            'zh-CN': '搜索 TypeScript API',
          },
          link: '/reference/api/typescript/',
        },
      ],
    },
    {
      label: 'CLI reference',
      translations: {
        en: 'CLI reference',
        es: 'Referencia de CLI',
        fr: 'Référence CLI',
        de: 'CLI-Referenz',
        it: 'Riferimento CLI',
        pt: 'Referência de CLI',
        ru: 'Справочник CLI',
        'zh-CN': 'CLI 参考',
        da: 'CLI-reference',
        hi: 'CLI संदर्भ',
        id: 'Referensi CLI',
        ja: 'CLI リファレンス',
        ko: 'CLI 참고서',
        'pt-BR': 'Referência de CLI',
        tr: 'CLI referansı',
        uk: 'CLI Довідник',
      },
      collapsed: false,
      items: [
        {
          label: 'Overview',
          translations: {
            da: 'Oversigt',
            de: 'Übersicht',
            en: 'Overview',
            es: 'Descripción general',
            fr: "Vue d'ensemble",
            hi: 'अवलोकन',
            id: 'Ikhtisar',
            it: 'Panoramica',
            ja: '概要',
            ko: '개요',
            pt: 'Visão geral',
            'pt-BR': 'Visão geral',
            ru: 'Обзор',
            tr: 'Genel Bakış',
            uk: 'Огляд',
            'zh-CN': '概述',
          },
          slug: 'reference/cli/overview',
        },
        {
          label: 'Install script',
          translations: {
            da: 'Installationsscript',
            de: 'Installationsskript',
            en: 'Install script',
            es: 'Script de instalación',
            fr: "Script d'installation",
            hi: 'इंस्टॉलेशन स्क्रिप्ट',
            id: 'Skrip Instalasi',
            it: 'Script di installazione',
            ja: 'インストールスクリプト',
            ko: '설치 스크립트',
            pt: 'Script de instalação',
            'pt-BR': 'Script de instalação',
            ru: 'Скрипт установки',
            tr: 'Kurulum Betiği',
            uk: 'Скрипт установки',
            'zh-CN': '安装脚本',
          },
          slug: 'reference/cli/install-script',
        },
        {
          label: 'Configuration',
          translations: {
            da: 'Konfiguration',
            de: 'Konfiguration',
            en: 'Configuration',
            es: 'Configuración',
            fr: 'Configuration',
            hi: 'कॉन्फ़िगरेशन',
            id: 'Konfigurasi',
            it: 'Configurazione',
            ja: '構成',
            ko: '구성',
            pt: 'Configuração',
            'pt-BR': 'Configuração',
            ru: 'Конфигурация',
            tr: 'Yapılandırma',
            uk: 'Конфігурація',
            'zh-CN': '配置',
          },
          slug: 'reference/cli/configuration',
        },
        {
          label: 'Microsoft telemetry',
          translations: {
            da: 'Microsoft telemetri',
            de: 'Microsoft-Telemetrie',
            en: 'Microsoft telemetry',
            es: 'Telemetría de Microsoft',
            fr: 'Télémétrie Microsoft',
            hi: 'Microsoft टेलीमेट्री',
            id: 'Telemetri Microsoft',
            it: 'Telemetria Microsoft',
            ja: 'Microsoft テレメトリ',
            ko: 'Microsoft 원격 분석',
            pt: 'Telemetria da Microsoft',
            'pt-BR': 'Telemetria da Microsoft',
            ru: 'Телеметрия Microsoft',
            tr: 'Microsoft telemetrisi',
            uk: 'Телеметрія Microsoft',
            'zh-CN': 'Microsoft 遥测',
          },
          slug: 'reference/cli/microsoft-collected-cli-telemetry',
        },
        {
          label: 'Commands',
          translations: {
            da: 'Kommandoer',
            de: 'Befehle',
            en: 'Commands',
            es: 'Comandos',
            fr: 'Commandes',
            hi: 'कमांड',
            id: 'Perintah',
            it: 'Comandi',
            ja: 'コマンド',
            ko: '명령어',
            pt: 'Comandos',
            'pt-BR': 'Comandos',
            ru: 'Команды',
            tr: 'Komutlar',
            uk: 'Команди',
            'zh-CN': '命令',
          },
          collapsed: true,
          items: [
            { label: 'aspire', slug: 'reference/cli/commands/aspire' },
            { label: 'aspire add', slug: 'reference/cli/commands/aspire-add' },
            {
              label: 'aspire agent',
              collapsed: true,
              items: [
                {
                  label: 'aspire agent',
                  slug: 'reference/cli/commands/aspire-agent',
                },
                {
                  label: 'aspire agent init',
                  slug: 'reference/cli/commands/aspire-agent-init',
                },
                {
                  label: 'aspire agent mcp',
                  slug: 'reference/cli/commands/aspire-agent-mcp',
                },
              ],
            },
            {
              label: 'aspire cache',
              collapsed: true,
              items: [
                {
                  label: 'aspire cache',
                  slug: 'reference/cli/commands/aspire-cache',
                },
                {
                  label: 'aspire cache clear',
                  slug: 'reference/cli/commands/aspire-cache-clear',
                },
              ],
            },
            {
              label: 'aspire certs',
              collapsed: true,
              items: [
                {
                  label: 'aspire certs',
                  slug: 'reference/cli/commands/aspire-certs',
                },
                {
                  label: 'aspire certs clean',
                  slug: 'reference/cli/commands/aspire-certs-clean',
                },
                {
                  label: 'aspire certs trust',
                  slug: 'reference/cli/commands/aspire-certs-trust',
                },
              ],
            },
            {
              label: 'aspire config',
              collapsed: true,
              items: [
                {
                  label: 'aspire config',
                  slug: 'reference/cli/commands/aspire-config',
                },
                {
                  label: 'aspire config delete',
                  slug: 'reference/cli/commands/aspire-config-delete',
                },
                {
                  label: 'aspire config get',
                  slug: 'reference/cli/commands/aspire-config-get',
                },
                {
                  label: 'aspire config list',
                  slug: 'reference/cli/commands/aspire-config-list',
                },
                {
                  label: 'aspire config set',
                  slug: 'reference/cli/commands/aspire-config-set',
                },
              ],
            },
            {
              label: 'aspire deploy',
              slug: 'reference/cli/commands/aspire-deploy',
            },
            {
              label: 'aspire describe',
              slug: 'reference/cli/commands/aspire-describe',
            },
            { label: 'aspire do', slug: 'reference/cli/commands/aspire-do' },
            {
              label: 'aspire docs',
              collapsed: true,
              items: [
                {
                  label: 'aspire docs',
                  slug: 'reference/cli/commands/aspire-docs',
                },
                {
                  label: 'aspire docs get',
                  slug: 'reference/cli/commands/aspire-docs-get',
                },
                {
                  label: 'aspire docs list',
                  slug: 'reference/cli/commands/aspire-docs-list',
                },
                {
                  label: 'aspire docs search',
                  slug: 'reference/cli/commands/aspire-docs-search',
                },
              ],
            },
            {
              label: 'aspire doctor',
              slug: 'reference/cli/commands/aspire-doctor',
            },
            {
              label: 'aspire export',
              slug: 'reference/cli/commands/aspire-export',
            },
            { label: 'aspire init', slug: 'reference/cli/commands/aspire-init' },
            {
              label: 'aspire logs',
              slug: 'reference/cli/commands/aspire-logs',
            },
            {
              label: 'aspire mcp',
              collapsed: true,
              items: [
                {
                  label: 'aspire mcp',
                  slug: 'reference/cli/commands/aspire-mcp',
                },
                {
                  label: 'aspire mcp call',
                  slug: 'reference/cli/commands/aspire-mcp-call',
                },
                {
                  label: 'aspire mcp tools',
                  slug: 'reference/cli/commands/aspire-mcp-tools',
                },
              ],
            },
            { label: 'aspire new', slug: 'reference/cli/commands/aspire-new' },
            {
              label: 'aspire otel',
              collapsed: true,
              items: [
                {
                  label: 'aspire otel',
                  slug: 'reference/cli/commands/aspire-otel',
                },
                {
                  label: 'aspire otel logs',
                  slug: 'reference/cli/commands/aspire-otel-logs',
                },
                {
                  label: 'aspire otel spans',
                  slug: 'reference/cli/commands/aspire-otel-spans',
                },
                {
                  label: 'aspire otel traces',
                  slug: 'reference/cli/commands/aspire-otel-traces',
                },
              ],
            },
            { label: 'aspire ps', slug: 'reference/cli/commands/aspire-ps' },
            {
              label: 'aspire publish',
              slug: 'reference/cli/commands/aspire-publish',
            },
            {
              label: 'aspire resource',
              slug: 'reference/cli/commands/aspire-resource',
            },
            {
              label: 'aspire restore',
              slug: 'reference/cli/commands/aspire-restore',
            },
            { label: 'aspire run', slug: 'reference/cli/commands/aspire-run' },
            {
              label: 'aspire secret',
              collapsed: true,
              items: [
                {
                  label: 'aspire secret',
                  slug: 'reference/cli/commands/aspire-secret',
                },
                {
                  label: 'aspire secret delete',
                  slug: 'reference/cli/commands/aspire-secret-delete',
                },
                {
                  label: 'aspire secret get',
                  slug: 'reference/cli/commands/aspire-secret-get',
                },
                {
                  label: 'aspire secret list',
                  slug: 'reference/cli/commands/aspire-secret-list',
                },
                {
                  label: 'aspire secret path',
                  slug: 'reference/cli/commands/aspire-secret-path',
                },
                {
                  label: 'aspire secret set',
                  slug: 'reference/cli/commands/aspire-secret-set',
                },
              ],
            },
            {
              label: 'aspire start',
              slug: 'reference/cli/commands/aspire-start',
            },
            { label: 'aspire stop', slug: 'reference/cli/commands/aspire-stop' },
            {
              label: 'aspire update',
              slug: 'reference/cli/commands/aspire-update',
            },
            {
              label: 'aspire wait',
              slug: 'reference/cli/commands/aspire-wait',
            },
          ],
        },
      ],
    },
    {
      label: 'Diagnostics',
      translations: {
        da: 'Diagnostik',
        de: 'Diagnose',
        en: 'Diagnostics',
        es: 'Diagnósticos',
        fr: 'Diagnostics',
        hi: 'निदान',
        id: 'Diagnostik',
        it: 'Diagnostica',
        ja: '診断',
        ko: '진단',
        pt: 'Diagnósticos',
        'pt-BR': 'Diagnósticos',
        ru: 'Диагностика',
        tr: 'Tanılama',
        uk: 'Діагностика',
        'zh-CN': '诊断',
      },
      collapsed: true,
      items: [
        { label: 'Overview', link: '/diagnostics/overview' },
        {
          label: 'Warnings',
          collapsed: true,
          items: [
            { label: 'ASPIRE001', link: '/diagnostics/aspire001' },
            { label: 'ASPIRE002', link: '/diagnostics/aspire002' },
            { label: 'ASPIRE003', link: '/diagnostics/aspire003' },
            { label: 'ASPIRE004', link: '/diagnostics/aspire004' },
            {
              label: 'ASPIREATS001',
              link: '/diagnostics/aspireats001',
            },
            {
              label: 'ASPIREEXPORT005',
              link: '/diagnostics/aspireexport005',
            },
            {
              label: 'ASPIREEXPORT006',
              link: '/diagnostics/aspireexport006',
            },
            {
              label: 'ASPIREEXPORT007',
              link: '/diagnostics/aspireexport007',
            },
            {
              label: 'ASPIREEXPORT008',
              link: '/diagnostics/aspireexport008',
            },
            {
              label: 'ASPIREEXPORT009',
              link: '/diagnostics/aspireexport009',
            },
            {
              label: 'ASPIREEXPORT010',
              link: '/diagnostics/aspireexport010',
            },
            {
              label: 'ASPIRECERTIFICATES001',
              link: '/diagnostics/aspirecertificates001',
            },
            {
              label: 'ASPIRECOMPUTE002',
              link: '/diagnostics/aspirecompute002',
            },
            {
              label: 'ASPIRECOMPUTE003',
              link: '/diagnostics/aspirecompute003',
            },
            {
              label: 'ASPIRECONTAINERRUNTIME001',
              link: '/diagnostics/aspirecontainerruntime001',
            },
            {
              label: 'ASPIRECONTAINERSHELLEXECUTION001',
              link: '/diagnostics/aspirecontainershellexecution001',
            },
            {
              label: 'ASPIREDOCKERFILEBUILDER001',
              link: '/diagnostics/aspiredockerfilebuilder001',
            },
            {
              label: 'ASPIREDOTNETTOOL',
              link: '/diagnostics/aspiredotnettool',
            },
            {
              label: 'ASPIREEXTENSION001',
              link: '/diagnostics/aspireextension001',
            },
            {
              label: 'ASPIREFILESYSTEM001',
              link: '/diagnostics/aspirefilesystem001',
            },
            {
              label: 'ASPIREINTERACTION001',
              link: '/diagnostics/aspireinteraction001',
            },
            {
              label: 'ASPIREMCP001',
              link: '/diagnostics/aspiremcp001',
            },
            {
              label: 'ASPIREPIPELINES004',
              link: '/diagnostics/aspirepipelines004',
            },
            {
              label: 'ASPIREPROBES001',
              link: '/diagnostics/aspireprobes001',
            },
            {
              label: 'ASPIREPOSTGRES001',
              link: '/diagnostics/aspirepostgres001',
            },
            {
              label: 'ASPIREUSERSECRETS001',
              link: '/diagnostics/aspireusersecrets001',
            },
          ],
        },
        {
          label: 'Errors',
          collapsed: true,
          items: [
            { label: 'ASPIRE006', link: '/diagnostics/aspire006' },
            { label: 'ASPIRE007', link: '/diagnostics/aspire007' },
            { label: 'ASPIRE008', link: '/diagnostics/aspire008' },
            {
              label: 'ASPIREACADOMAIN001',
              link: '/diagnostics/aspireacadomains001',
            },
            { label: 'ASPIRECOMPUTE001', link: '/diagnostics/aspirecompute001' },
            {
              label: 'ASPIRECSHARPAPPS001',
              link: '/diagnostics/aspirecsharpapps001',
            },
            {
              label: 'ASPIRECOSMOSDB001',
              link: '/diagnostics/aspirecosmosdb001',
            },
            {
              label: 'ASPIREEXPORT001',
              link: '/diagnostics/aspireexport001',
            },
            {
              label: 'ASPIREEXPORT002',
              link: '/diagnostics/aspireexport002',
            },
            {
              label: 'ASPIREEXPORT003',
              link: '/diagnostics/aspireexport003',
            },
            {
              label: 'ASPIREEXPORT004',
              link: '/diagnostics/aspireexport004',
            },
            {
              label: 'ASPIREHOSTINGPYTHON001',
              link: '/diagnostics/aspirehostingpython001',
            },
            {
              label: 'ASPIREPIPELINES001',
              link: '/diagnostics/aspirepipelines001',
            },
            {
              label: 'ASPIREPIPELINES002',
              link: '/diagnostics/aspirepipelines002',
            },
            {
              label: 'ASPIREPIPELINES003',
              link: '/diagnostics/aspirepipelines003',
            },
            {
              label: 'ASPIREPROXYENDPOINTS001',
              link: '/diagnostics/aspireproxyendpoints001',
            },
            {
              label: 'ASPIREPUBLISHERS001',
              link: '/diagnostics/aspirepublishers001',
            },
            { label: 'ASPIREAZURE001', link: '/diagnostics/aspireazure001' },
            { label: 'ASPIREAZURE002', link: '/diagnostics/aspireazure002' },
            { label: 'ASPIREAZURE003', link: '/diagnostics/aspireazure003' },
          ],
        },
      ],
    },
    {
      label: 'Support',
      translations: {
        da: 'Support',
        de: 'Support',
        en: 'Support',
        es: 'Soporte',
        fr: 'Support',
        hi: 'समर्थन',
        id: 'Dukungan',
        it: 'Supporto',
        ja: 'サポート',
        ko: '지원',
        pt: 'Suporte',
        'pt-BR': 'Suporte',
        ru: 'Поддержка',
        tr: 'Destek',
        uk: 'Підтримка',
        'zh-CN': '支持',
      },
      link: '/support/',
    },
  ],
};
