export const redirects = {
  // https://docs.astro.build/en/guides/routing/#configured-redirects
  // For example:
  // '/original/path/': '/new/path'
  '/get-started/welcome/': '/docs/',
  '/integrations/postgres/': '/integrations/databases/postgres/postgres-get-started/',
  '/integrations/databases/milvus/': '/integrations/databases/milvus/milvus-get-started/',
  '/integrations/databases/qdrant/': '/integrations/databases/qdrant/qdrant-get-started/',
  '/integrations/oracle/': '/integrations/databases/efcore/oracle/oracle-get-started/',
  '/integrations/sqlite/': '/integrations/databases/sqlite/sqlite-get-started/',
  '/integrations/sql-server/': '/integrations/databases/sql-server/sql-server-get-started/',
  '/integrations/mysql/': '/integrations/databases/mysql/mysql-get-started/',
  '/integrations/rabbitmq/': '/integrations/messaging/rabbitmq/rabbitmq-get-started/',
  '/integrations/eventstore/': '/integrations/databases/kurrentdb/',
  '/integrations/databases/efcore/mssql/': '/integrations/databases/efcore/mysql/mysql-get-started/',
  '/integrations/databases/mongodb/': '/integrations/databases/mongodb/mongodb-get-started/',
  '/integrations/databases/mongodb-extensions/': '/integrations/databases/mongodb/mongodb-extensions/',
  '/integrations/databases/efcore/azure-cosmos-db/': '/integrations/databases/efcore/azure-cosmos-db/azure-cosmos-db-get-started/',
  '/integrations/databases/oracle-ef/': '/integrations/databases/efcore/oracle/oracle-get-started/',
  '/integrations/databases/elasticsearch/': '/integrations/databases/elasticsearch/elasticsearch-get-started/',
  '/integrations/cloud/azure/azure-postgresql/': '/integrations/cloud/azure/azure-postgresql/azure-postgresql-get-started/',
  '/integrations/databases/efcore/sql-server/': '/integrations/databases/efcore/sql-server/sql-server-get-started/',
  '/integrations/databases/efcore/postgresql/': '/integrations/databases/efcore/postgres/postgresql-get-started/',
  '/integrations/databases/efcore/azure-postgresql/': '/integrations/databases/efcore/azure-postgresql/azure-postgresql-get-started/',
  '/integrations/databases/efcore/azure-sql/': '/integrations/databases/efcore/azure-sql/azure-sql-get-started/',
  // Redirects for restructured integrations (Feb 2026)
  '/integrations/ai/github-models/': '/integrations/ai/github-models/github-models-get-started/',
  '/integrations/ai/openai/': '/integrations/ai/openai/openai-get-started/',
  '/integrations/caching/redis/': '/integrations/caching/redis/redis-get-started/',
  '/integrations/caching/redis-distributed/': '/integrations/caching/redis-distributed/redis-distributed-get-started/',
  '/integrations/caching/redis-output/': '/integrations/caching/redis-output/redis-output-get-started/',
  '/integrations/caching/valkey/': '/integrations/caching/valkey/valkey-get-started/',
  '/integrations/caching/garnet/': '/integrations/caching/garnet/garnet-get-started/',
  '/integrations/messaging/apache-kafka/': '/integrations/messaging/apache-kafka/apache-kafka-get-started/',
  '/integrations/messaging/nats/': '/integrations/messaging/nats/nats-get-started/',
  '/integrations/observability/seq/': '/integrations/observability/seq/seq-get-started/',
};
